### ISSUE TITLE
Python 2 is Sunset, its installation should be removed from the Content Guide

### ISSUE THREAD

**Issue by juanda2** [CiscoDevNet/devnet-express-dna-issues#100]
Hello DevNet,

on https://developer.cisco.com/learning/devnet-express/dnav4-track/dev-setup/dev-win/step/5 the guide asks to install python 2 with this reason:
"many scripts and programs were written in Python 2 and have yet to be upgraded"

however, Python 2 has been officially sunset and the Python 2 / 3 confusion is creating more problems for our DevNet Express students than it is solving. They're getting frustrated with how different operating systems behave with these two conflicting versions.

Happy to discuss further, Thanks so much for the amazing content!

David Fernandez

**Comment by klevenstein** [comment]
Hi David - we're working out how to best address the Python 2 issue and should have something soon. Thanks!

**Comment by makarthi** [comment]
HI Team, I am not able to get pip install -r requirements.txt to work? It is failing on Cisco Spark API.
Can somebody help?

**Comment by annegentle** [comment]
Hi, you want to update the requirements.txt file to have 
webexteamssdk
instead of 

ciscosparkapi 

Edit the file, save it, then re-run `pip install -r requirements.txt`. Let us know if that works. 

You can see more about the library at:
https://github.com/CiscoDevNet/webexteamssdk

**Comment by klevenstein** [comment]
@juanda2 We've moved the Python 2 content to Appendices in the setup labs (see also https://github.com/CiscoDevNet/dev-setup-labs/pull/25). Hopefully that addresses your concerns.

**Comment by annegentle** [comment]
I think this Issue can be closed since the concern has been addressed. Feel free to re-open if needed.
