### ISSUE TITLE
Postman instructions are not clear

### ISSUE THREAD

**Issue by ignaciofite** [CiscoDevNet/devnet-express-dna-issues#102]
In the following page: https://developer.cisco.com/learning/devnet-express/dnav4-track/dnav4-intro-dnac/dne-dnac-auth/step/1
When try to get the token with Postman most of the event attendees try to copy and past Basic YWRtaW46R3JhcGV2aW5lMQ==, the instructions should specify that they need to use the authorization tab to input the credentials there,

**Comment by klevenstein** [comment]
Fixes submitted for review. @kiskander can you review?

**Comment by klevenstein** [comment]
Fix published: https://developer.cisco.com/learning/lab/dne-dnac-auth/step/1
