### ISSUE TITLE
Step https://developer.cisco.com/learning/devnet-express/dnav4-track/dnav4-intro-dnac/dne-dnac-auth/step/2 has wrong import

### ISSUE THREAD

**Issue by ignaciofite** [CiscoDevNet/devnet-express-dna-issues#103]
When attendees try to run the code in https://developer.cisco.com/learning/devnet-express/dnav4-track/dnav4-intro-dnac/dne-dnac-auth/step/2, specifically the import:
`from dnac_config import DNAC, DNAC_PORT, DNAC_USER, DNAC_PASSWORD`
it usually fails because nowhere in the instructions says that they should run it in the same folder as `env_lab.py` this should be more clear on the instructions.

**Comment by klevenstein** [comment]
Fixes submitted for review. @kiskander can you review?

**Comment by klevenstein** [comment]
Fix published: https://developer.cisco.com/learning/lab/dne-dnac-auth/step/2
