### ISSUE TITLE
Instructions not clear enough in https://developer.cisco.com/learning/devnet-express/dnav4-track/dnav4-intro-dnac/dne-dnac-path-trace/step/2

### ISSUE THREAD

**Issue by ignaciofite** [CiscoDevNet/devnet-express-dna-issues#104]
When attendees try to do the following on Postman:
![image](https://user-images.githubusercontent.com/15130412/79860229-938bb980-83d2-11ea-9298-b787142c1140.png)
they sometimes fail because the instructions don't specify to put that in the body as raw, that might seem trivial but it is not for some people...

**Comment by klevenstein** [comment]
Fixes submitted for review. @kiskander can you review?

**Comment by klevenstein** [comment]
Fix published: https://developer.cisco.com/learning/lab/dne-dnac-auth/step/2
