### ISSUE TITLE
DNEv4 Confusing screenshots in DNA Modul 

### ISSUE THREAD

**Issue by pheilmei** [CiscoDevNet/devnet-express-dna-issues#108]
https://developer.cisco.com/learning/devnet-express/dnav4-track/dnav4-intro-dnac/dne-dnac-auth/step/1
https://developer.cisco.com/learning/devnet-express/dnav4-track/dnav4-intro-dnac/dne-dnac-network-device/step/2

In the module description following endpoint url is used: https://sandboxdnac2.cisco.com
In the screenshots the https://sandboxdnac.cisco.com is used this confuse the attendees
Please make consistent screenshot, aligned to the description

**Comment by kiskander** [comment]
both sandboxes are used interchangeably depending on SB upgrade/availability  . we can either keep it as is or just put an Agnostic server like `{Your Instance of DNAC HERE}' in the screenshot

**Comment by klevenstein** [comment]
Touching all of the screenshots can be a fairly heavy undertaking. It may be easier to simply include a note to the effect that the student should use the Sandbox URL in the instructions, and the screenshots are provided for clarity.

**Comment by vvaliapa** [comment]
Updated the postman screenshots and added a note regarding the https://sandboxdnac2.cisco.com and https://sandboxdnac.cisco.com urls.
