### ISSUE TITLE
DNEv4 10.10.22.74 ipaddress is not available 

### ISSUE THREAD

**Issue by pheilmei** [CiscoDevNet/devnet-express-dna-issues#109]
https://developer.cisco.com/learning/devnet-express/dnav4-track/dnav4-intro-dnac/dne-dnac-network-device/step/2

Attendees try to use the the managementIpAddress 10.10.22.74 in the screenshot, which  is not available on API Endpoint https://sandboxdnac2.cisco.com

Please suggest an available ip on the to used DNAC as API Endpoint, or use a description which allows a user to choose by self a IP address

**Comment by vvaliapa** [comment]
Updated the screenshots and added a note about the device IPs in  https://developer.cisco.com/learning/devnet-express/dnav4-track/dnav4-intro-dnac/dne-dnac-network-device/step/2.
