### ISSUE TITLE
LM-4201: Update slides 

### ISSUE THREAD

**Issue by austinMarcos** [CiscoDevNet/devnet-express-dna-issues#11]
USER STORY:  As a host, I need a better storyline about why this event is useful in understanding the DNA tools and technology.

Need to explain the reason that network and infrastructure engineers need to understand the role of APIs from the point of view of an app developer putting pressure on the infrastructure to support mobile devices.

These updates to the slides DO NOT affect the demo or existing labs.

**Comment by austinMarcos** [comment]
On April 10, Chris L., Chris O., Brett, Armen, and Darien reviewed the slides that Chris O has updated. All agreed on changes except for one slide. Chris O. will amend, and then we will review and approve for distribution.

**Comment by RuthCattell** [comment]
Is there an update on the slide review?

**Comment by RuthCattell** [comment]
Chris O put the following comment in the Spark room:
"Hi Team - I've done more work on this. I need help on slide 18 - also, I'm wondering if you think we need all the slides after slide 30. For me, as an intro to DNA, I think it just goes on and on and on….we could shorten this entire segment and jump into the meat of the session. I think we could drop at least 2/3 of the slides after 30…but I haven't done it until we talk or I get some feedback. Attachment to follow".

So where does this leave us re the ShowStopper issue @austinMarcos ?  
I've put Chris' slides in the box: https://cisco.box.com/s/1yq8laujovbm6ycd5fiw73haekudkfn0

**Comment by austinMarcos** [comment]
1. I incorporate 2 slides from Chris O. The slides have the titles "The Cisco Application Centric Platform". I inserted them right before the slide for the demo. 
2. I added a short note to the slide for the demo to point to the instructions in the Word document that explains how to set up the demo.

These changes are all that is needed for this Post-Berlin update for showstoppers. Further changes to the slide deck might come from Chris O. at a later time.

**Comment by RuthCattell** [comment]
Updated FINAL PUBLISH SLIDES folder for LM-4201 with new slides, demo notes and a Release Notes box note.
https://cisco.box.com/s/pdlqz2sozox4tb4d0bavgji62vnf31n5

**Comment by austinMarcos** [comment]
@cmlccie I see that you re-opened this issue. Is there something left to do on the slides for LM-4201?

**Comment by cmlccie** [comment]
Yes, I reopened this issue as the slides that were added don't "make sense" (referring to APIs and capabilities in the wrong places) and aren't what we had agreed upon would be done with this ask.  The slides included were Chris O.'s placeholders.  Actual factual and visually appealing slides were to be created and included (perhaps with the help of the tiger team).

**Comment by austinMarcos** [comment]
Slides updated with new slides from Chris O. Removed other placeholder slides.

**Comment by austinMarcos** [comment]
Closing issue due to aging. This issue was fixed and rolled out to production.
