### ISSUE TITLE
DNEv4 confusing query param description in DNAC Modul

### ISSUE THREAD

**Issue by pheilmei** [CiscoDevNet/devnet-express-dna-issues#110]
https://developer.cisco.com/learning/devnet-express/dnav4-track/dnav4-intro-dnac/dne-dnac-network-device/step/2

If you do the steps as described in the Modul to add the managementIpAddress or macAddress in Postman, user ends with an misleading Endpoint API

Endpoint API generated by Postman as described in modul:
https://sandboxdnac2.cisco.com/api/v1/network-device?managementIpAddress=10.10.22.74&macAddress=00:c8:8b:80:bb:00

correct API:
https://sandboxdnac2.cisco.com/api/v1/network-device/?managementIpAddress=10.10.22.74&macAddress=00:c8:8b:80:bb:00

Furthermore the IP Adress is wrong, [reported in this Issue](https://github.com/CiscoDevNet/devnet-express-dna-issues/issues/109)

**Comment by vvaliapa** [comment]
Fixed the issue.
