### ISSUE TITLE
Login to Webex failed using cco account

### ISSUE THREAD

**Issue by Geevarghese** [CiscoDevNet/devnet-express-dna-issues#114]
For DNA > DNE > Virtual > May 18-19 2021 event one customer complained that When he is trying to login using the Webex Teams authentication, he receives the following error message:
fail to get user from state: oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"The provided access grant is invalid, expired, or revoked.","trackingID":"
Have asked to login  https://developer.webex.com/ with cco credentials and then try to login webex. It worked .. But the customer wanted "would there be a place to suggest to change the error message to something more explicit?" Hence logging the issue..

**Comment by dethanga** [comment]
Hi @annegentle and @klevenstein 
cc @Geevarghese 
As discussed with Gee, I understood that the user did not try logging in via browser. Or it might be any network issues the user was facing during the Virtual event. Also, it is observed we got this issue from one user. 
That's said, there would not be an issue with the Teams specific. Hence I am closing this issue. 

Thanks - Devi
