### ISSUE TITLE
Linkage from powerpoints to labs is weak

### ISSUE THREAD

**Issue by securenetwrk** [CiscoDevNet/devnet-express-dna-issues#12]
After our event last week we had pretty consistent feedback that the Power Points and labs online were not as closely aligned as would be ideal, and it led to a lot of confusion. In many cases there were some overlapping topics and images, but others were in one or the other. When moving from the slides to a lab, it wasn't clear what lab to move to. The Nomenclature in the slides refers to "Lab X Step Y" but on the site it just has a description for the Lab and within there a few pages which correspond to steps. Labeling each "Lab" with the same number as the slides and having direct links to each step within may help reduce the confusion. If the feedback isn't clear between this and the feedback from San Diego please let me know and I will help clarify.

**Comment by brtiller1** [comment]
Thanks for your feedback.  We had recently recoded/modified modules and still needed to update the corresponding slide decks which is now done.  We don’t provide direct links in the slide decks to the labs as it’s better and clearer for the trainer to show how to access the labs and the steps therein.  Please take a look at the latest slide decks and let us know your thoughts.

Brett
[http://www.cisco.com/web/europe/images/email/signature/logo05.jpg]

Brett Tiller
ENGINEER.CUSTOM APPLICATION
brtiller@cisco.com
Phone: +1 919 392 3307
DevNet
http://developer.cisco.com

Cisco Systems Limited
7025-6 Kit Creek Road PO Box 14987
RESEARCH TRIANGLE PARK
NORTH CAROLINA
27709-4987
US

**Comment by securenetwrk** [comment]
This is no longer applicable.
