### ISSUE TITLE
LM-4901 CMX Mission cannot be finished

### ISSUE THREAD

**Issue by austinMarcos** [CiscoDevNet/devnet-express-dna-issues#16]
User Story:  As a host of DevNet events, I need a CMX mission that can be performed by multiple users at the same time. LM-4901: Using the Cisco Location Based Services

-  The new mission needs to show a use-case that is not limited by the constraint on multiple concurrent users.  The way the current mission is written, multiple uses cannot access the CMX notification port simultaneously because of the security policies built in to the CMS server.
-  Use Python as the basis for the sample code.
-  Indicate revised mission on the module so that hosts know that the module has been revised

**Comment by austinMarcos** [comment]
Matt:  Can you please update the status on this (as you did in email).

**Comment by matthewjfarrell** [comment]
Lab 09-cmx-04-cmx-and-mse-mission-01 under DevNet Express has been updated with coding examples to use CMX API in Python.  CMX Mission title changed to "Mission: Query the CMX API using Python scripts" and Python 3 code examples are located at /github/devnet-express-code-samples/module09.  
IMPORTANT NOTE:  CMX 10 URL is changed to https://cmxlocationsandbox.cisco.com/api for access to the CMX API resources.  This name change will not switch over until EOD Friday, April 21.  Until then use the old CMX URL for API calls, https://msesandbox.cisco.com:8081/api.

**Comment by austinMarcos** [comment]
From: Yawming Chen (yawchen) 
Sent: Tuesday, April 18, 2017 4:09 PM

I am not really starting walk through the lab yet but just trying to run couple of sample codes in the mission - https://learninglabs.cisco.com:8867/tracks/devnet-express-dna/cmx/09-cmx-04-cmx-and-mse-mission-01/step/1
sampleRESTcode.py
clientcount.py

I think we may want to modify those codes.

sampleRESTcode.py - This sample code is from CMX UI – API reference. I see 2 issues here
1.       It’s in a loop that we can try different AP, good  but once we missed providing right username and password then we are in a loop of error. It won’t ask credential again and the script will make a request with wrong credential.
2.       If we hit the “except” we should do the system exit otherwise we will be in the loop of “except”
clientcount.py – Same as 2nd point above, if we hit “except” we will be in a loop. For example ,I ran the script and had SSL issue then it went into a loop of the following:


[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:645)
[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:645)
[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:645)
[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:645)
[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:645)
[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:645)
[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:645)


Thanks,

Yawming

**Comment by austinMarcos** [comment]
From: Matthew Farrell
Sent: Tuesday, April 18, 2017 4:21 PM

Yawming,

If you’re on a mac you will need the latest version of openssl module.
msesandbox.cisco.com:8081
This server supports only TLS 1.2, i.e. no TLS 1.0 or worse.
'OpenSSL 0.9.8zg 14 July 2015'
This OpenSSL version does not support TLS 1.2 yet. You need at least OpenSSL 1.0.1 for this.

$openssl version
$brew update
$brew install --force openssl
$echo 'export PATH="/usr/local/opt/openssl/bin:$PATH"' >> ~/.bash_profile

Or try it on your Ubuntu pod workstation.  
ssh learning@128.107.70.29 learning/learning is also available.

Matt

**Comment by austinMarcos** [comment]
From: Yawming Chen (yawchen) 
Sent: Tuesday, April 18, 2017 4:43 PM

Python 3.6 has OpenSSL 1.0.2 works fine too.

Is “clientcount.py” used in subsequent labs for modification? Why we use loop here?

Thanks,

Yawming

**Comment by austinMarcos** [comment]
From: Matthew Farrell -X 
Sent: Tuesday, April 18, 2017 5:01 PM

Yes, we demo the loop function here which will be used in additional exercises with mac addresses.  Matt
Good to know regarding Python 3.6!
Thanks,
Matt

**Comment by RuthCattell** [comment]
Can Matt Denapoli look at this too (if he hasn't already done so?)  He's the CMX / Meraki Dev Evanglist and therefore one of the SME owners.

**Comment by matthewjfarrell** [comment]
The CMX Mission learning lab is complete and is being reviewed by Yawming.  The DevNet sandbox team is ready to switch over to new url for CMX sandbox https://cmxlocationsandbox.cisco.com, on Friday, April 28.  Let us know if this date is still good.  Thanks, Matt

**Comment by yawming** [comment]
Now we can reach the new Sandbox  https://cmxlocationsandbox.cisco.com and all sample codes are working fine. 

The only left that I have noticed is the sample code, sampleRESTcode.py,in first mission - "Query the CMX API using Python scripts" which I understand is from the CMX API sample. When running this sample code if we enter the wrong username or password will get errors that looks like something else but actually is just authentication issue.

Traceback (most recent call last):
  File "/DNE/DNA Track/devnet-express-code-samples/module09/sampleRESTcode.py", line 52, in <module>
    main()
  File "/DNE/DNA Track/devnet-express-code-samples/module09/sampleRESTcode.py", line 44, in main
    print(json.dumps(parsed(), indent=2))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/models.py", line 858, in json
    self.content.decode(encoding), **kwargs
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by RuthCattell** [comment]
@austinMarcos - Can I have the Release notes please if this is now ready to go???

**Comment by cmlccie** [comment]
Reopenning as Release Notes were not provided for this substantive change.

**Comment by austinMarcos** [comment]
Content published on May 3.
