### ISSUE TITLE
LM-4602:  Device Level Interfaces - pyang doesn't work on Windows when using Command Prompt

### ISSUE THREAD

**Issue by cmlccie** [CiscoDevNet/devnet-express-dna-issues#17]
**Lab-ID:**  dna-restconf-netconf-yang

Starting in the `Introduction to YANG Data Modeling`, and throughout the module we ask participants to use the [pyang](https://github.com/mbj4668/pyang) module to examine and interact with downloaded YANG data models; however, the instructions will not work for users using Windows and the Windows Command Line.

See https://github.com/mbj4668/pyang/issues/310 for more details.

**Workaround:**  Use a BASH shell, like [Git BASH](https://git-for-windows.github.io/), on Windows.

**Comment by austinMarcos** [comment]
Workaround:  add note to the lab to notify user that there is a known issue with the pyang package.  Using Gitbash would be our recommended workaround (or any bash shell for the command line).

**Comment by hpreston** [comment]
I'll review the lab docs and run it on the windows machine.  I know I've never had issues doing any of the exercises on the Windows box so I'll see if I can identify what is different and clear up any confusion in the lab guide.

**Comment by hremond** [comment]
For our event (DNE for DNA - Lausanne), we found another workaround : windows users needed to type in _python ..\Scripts\pyang -f tree ietf-interfaces.yang_ and it worked (.. being \Users\userid\Code\mycode). 
Worth updating the lab docs (took us 30 min to figure it out...)

**Comment by cmlccie** [comment]
@hremond and @hpreston , yes, the issue at it's core is an execution and path issue, which @hremond 's workaround corrects both:

1. Using `python` before the script name (causes Windows to run the file using the python interpreter)
2. Using the full (relative in this case) path to the `pyang` script.

Either this or use of a bash shell should be suitable workarounds.  Note that providing the full path to the `pyang` script may be a challenge given the variableness in the users' development environments (and the inconsistency in the track's directory structure #19 ).

**Comment by hpreston** [comment]
@cmlccie 

Though other methods of running the exercises with the standard command prompt may work, for the best experience all the labs should be run using the git bash interface, leveraging the proper icon on the desktop. 

Does this work for you to resolve this issue.  At the start of each example, I'll add a note in the Lab that says: 

**Note: ** if you are running these labs from the Windows server within the dCloud Sandbox, be sure to open a terminal using the blue, red, green and yellow icon on the desktop labeled "Use me as a Terminal".  This will open a Git Bash interface with the proper Python Virtual Environment activated.  

Thoughts?

**Comment by cmlccie** [comment]
That certainly works for those using the dCloud Windows environment, but it probably doesn't address those running into this when using their own Windows laptops.

**Comment by hpreston** [comment]
@cmlccie - correct... I'll adjust slightly to try to cover the BYOD model, but there is only so much possible for those cases.... and why I am leading the charge around dCloud only for DNE :-)

**Comment by hpreston** [comment]
Changes have been made in the Labs and pushed to Staging.  Awaiting info on when to push to prod.

**Comment by austinMarcos** [comment]
Verified that the note has been added to [the yang lab on production server](https://learninglabs.cisco.com/tracks/devnet-express-dna/dna-restconf-netconf-yang/06-dmi-02-introducing-yang-data-modeling/step/4).

@cmlccie - Can you please verify the fix and close the issue?

**Comment by cmlccie** [comment]
It would be nice if we could call out important notices and work-arounds with some sort of visual highlight.  This notice as it is easily blends into the text and might be easily overlooked.

<img width="1078" alt="cisco_devnet_learning_labs" src="https://cloud.githubusercontent.com/assets/16244946/26176223/67df04a4-3b23-11e7-8abe-df2fc2050798.png">

**Comment by austinMarcos** [comment]
Received message in Spark:
> Charles Eckel8:13 AM
> One big problem I hit today is that pyang is not available in Windows after going through the 
> environment setup on the first lab. What we found is that a Python script called pyang is created, but it 
> exists in the ./Scripts directory. This directory needs to be added into the path or called explicitly by the 
> user as "python pyang xxx"

Need to understand whether the Windows command window can be used to access pyang or run ANY of the python scripts without a workaraound. We need to look at possibility of updating the way Python is installed on the dCloud Windows workstation.
