### ISSUE TITLE
Verification Script Enhancement: Lab 03 Module 03 script enhancement request

### ISSUE THREAD

**Issue by armartirosyan** [CiscoDevNet/devnet-express-dna-issues#2]
ISSUE DESCRIPTION:

The `check_dcloud.py` script needs another method to verify that APIC-EM is active and is working properly.

**Comment by annegentle** [comment]
@austinMarcos Can this issue be closed or is it waiting on the dCloud pod image update?

**Comment by annegentle** [comment]
These code examples are now archived, closing.
