### ISSUE TITLE
Test Connectivity to the Lab Environment (dCloud Pod)

### ISSUE THREAD

**Issue by cmlccie** [CiscoDevNet/devnet-express-dna-issues#20]
**Lab-Id:**  00-pre-event-preparation
Test Connectivity to the Lab Environment (dCloud Pod) step has the participants connect to some other AnyConnect site rather than their assigned lab pod.  This causes participant confusion and adds unnecessary extra steps.

Some will follow the instructions and connect to this 'test VPN' connection and then wonder later why they cannot access their pod resources (now connected to the wrong backend environment).

Others will connect to their pod and then wonder why they cannot access the 'Test Page' called out in the test connectivity step (it doesn't existing in the DNA dCloud pods).

Others might follow all of the instructions and needlessly connect to two backend VPNs.

We should really just have them connect to 'their pod' and thing provide a verification step to confirm that they are properly connected (perhaps have them run the 'lab verification script').

**Comment by klevenstein** [comment]
PRs closed.
