### ISSUE TITLE
Users are instructed to download the Git repo multiple times

### ISSUE THREAD

**Issue by cmlccie** [CiscoDevNet/devnet-express-dna-issues#21]
**Lab-Ids:**

- 00-pre-event-preparation
- devnet-express-np-rest-apic
- others?...

We provide instructions to download the devnet-code-samples repo more than once throughout the track, and when coupled with #19 this causes some participants to rightfully do so and end up with multiple copies of the code on their machines, which causes UX issues like people editing code in one folder and then trying to run the scripts that are located in another (fun troubleshooting experience for new coders).

Downloading the Git repo should probably only be done in the setup module.

**Comment by austinMarcos** [comment]
@jamesneimanconsulting
The modules are published here:
  -  https://learninglabs.cisco.com/tracks/devnet-express-dna
 
For example, one of the lab IDs is:
   - 00-prep-01-prep-before-you-go-windows-dcloud

Sources for this can be found:
  -  devnet-express-code-samples

Repo with lab content:
  -  https://github.com/CiscoDevNet/devnet-express/tree/master/labs

**Comment by jamesneimanconsulting** [comment]
@austinMarcos I've checked all the files into git. There are quite a few so not sure whether we need to run production on each of the labs. For the record, here is what changed in git:
modified: labs/00-prep-01-prep-before-you-go-linux-dcloud/2.md
modified: labs/00-prep-01-prep-before-you-go-linux-host/1.md
modified: labs/00-prep-01-prep-before-you-go-mac-dcloud/2.md
modified: labs/00-prep-01-prep-before-you-go-mac-host/1.md
modified: labs/00-prep-01-prep-before-you-go-windows-host/1.md
modified: labs/00-prep-01-prep-before-you-go/1.md
modified: labs/00-prep-02-overview-of-rest-apis/.DS_Store
modified: labs/00-prep-02-overview-of-rest-apis/05-apic-04-mission/1.md
modified: labs/00-prep-03-python-primer/1.md
modified: labs/00-prep-04-python-primer2/1.md
modified: labs/00-prep-05-python-json/1.md
modified: labs/03-environment-02-accessing-the-lab-environment/2.md
modified: labs/03-environment-03-mission/1.md
modified: labs/04-rest-03-interfacing-with-rest-apis-using-python/.DS_Store
modified: labs/04-rest-03-interfacing-with-rest-apis-using-python/05-apic-04-mission/1.md
modified: labs/04-rest-03-interfacing-with-rest-apis-using-python/1.md
modified: labs/04-rest-04-coding-python-json/1.md
modified: labs/04-rest-04-coding-python-json/2.md
modified: labs/04-rest-04-learning-python-json/1.md
modified: labs/04-rest-04-learning-python-json/6.md
modified: labs/04-rest-05-mission/1.md
modified: labs/05-apic-03-apic-em-rest-api-python-app/1.md
modified: labs/05-apic-04-mission/1.md
modified: labs/06-dmi-01-introduction-to-standard-device-interfaces/lab.md
modified: labs/06-dmi-01-overview-of-device-level-netconf/1.md
modified: labs/06-dmi-01-overview-of-device-level-netconf/5.md
modified: labs/06-dmi-02-introducing-yang-data-modeling/4.md
modified: labs/06-dmi-02-introducing-yang-data-modeling/lab 2 - yang.md
modified: labs/06-dmi-02-yang-data-modeling-overview/4.md
modified: labs/06-dmi-02-yang-data-modeling-overview/5.md
modified: labs/06-dmi-02-yang-data-modeling-overview/7.md
modified: labs/06-dmi-03-using-restconf-to-interface-with-networking-devices/1.md
modified: labs/06-dmi-04-mission/1.md
modified: labs/06-dmi-04-mission/3.md
modified: labs/06-dmi-04-mission/4.md
modified: labs/06-dmi-05-mission/1.md
modified: labs/06-dmi-05-mission/4.md
modified: labs/07-virl-03-using-virl-test-apis/1.md
modified: labs/07-virl-04-mission/1.md
modified: labs/07-virl-04-mission/3.md
modified: labs/07-virl-04-mission/9.md
modified: labs/08-1-human-interaction-01-spark/1.md
modified: labs/08-human-interaction-01-spark-and-tropo/1.md
modified: labs/09-cmx-04-cmx-and-mse-mission-01/1.md
modified: labs/09-cmx-04-cmx-and-mse-mission-01/2.md
modified: labs/09-cmx-04-cmx-and-mse-mission-01/3.md
modified: labs/09-cmx-04-cmx-and-mse-mission-01/4.md
modified: labs/09-cmx-04-cmx-and-mse-mission-01/5.md
modified: labs/11-meraki-02-dashboard-api/1.md
modified: labs/11-meraki-03-click-through-captive-portal/1.md

**Comment by annegentle** [comment]
Should we consider this fixed?

**Comment by annegentle** [comment]
These Labs have been re-written for the DNAv3 track.
