### ISSUE TITLE
LM-4002 or LM-1201:  Should provide instructions on how to activate and deactivate a virtual environment

### ISSUE THREAD

**Issue by cmlccie** [CiscoDevNet/devnet-express-dna-issues#22]
We should provide instructions on how to activate and deactivate a virtual environment.  Without this, participants are often receiving 'import errors' because their packages were installed in their virtual environment, which they haven't activated when trying to run their scripts later on in the event.

If combined with a standardized folder structure (see #19), the instructions can be very simple (and should be coupled with a little explanation of how these work):

**Linux**
`source ~/dev/dna/venv/bin/activate`

**Windows**
`%HOMEPATH%\dev\dna\venv\Scripts\activate.bat`

**Deactivation - Both Platforms**
`deactivate`

**Comment by cmlccie** [comment]
I inadvertently created a duplicate to issue #4 .

**Comment by austinMarcos** [comment]
@jamesneimanconsulting 
The modules are published here:
  - https://learninglabs.cisco.com/tracks/devnet-express-dna
For example, one of the lab IDs is:
  - 00-prep-01-prep-before-you-go-windows-dcloud
Sources for this can be found:
  - devnet-express-code-samples
  - Repo with lab content:<br>https://github.com/CiscoDevNet/devnet-express/tree/master/labs

**Comment by jamesneimanconsulting** [comment]
@austinMarcos I've checked all the files into git. There are quite a few so not sure whether we need  to run production on each of the labs. For the record, here is what changed in git:
	modified:   labs/00-prep-01-prep-before-you-go-linux-dcloud/2.md
	modified:   labs/00-prep-01-prep-before-you-go-linux-host/1.md
	modified:   labs/00-prep-01-prep-before-you-go-mac-dcloud/2.md
	modified:   labs/00-prep-01-prep-before-you-go-mac-host/1.md
	modified:   labs/00-prep-01-prep-before-you-go-windows-host/1.md
	modified:   labs/00-prep-01-prep-before-you-go/1.md
	modified:   labs/00-prep-02-overview-of-rest-apis/.DS_Store
	modified:   labs/00-prep-02-overview-of-rest-apis/05-apic-04-mission/1.md
	modified:   labs/00-prep-03-python-primer/1.md
	modified:   labs/00-prep-04-python-primer2/1.md
	modified:   labs/00-prep-05-python-json/1.md
	modified:   labs/03-environment-02-accessing-the-lab-environment/2.md
	modified:   labs/03-environment-03-mission/1.md
	modified:   labs/04-rest-03-interfacing-with-rest-apis-using-python/.DS_Store
	modified:   labs/04-rest-03-interfacing-with-rest-apis-using-python/05-apic-04-mission/1.md
	modified:   labs/04-rest-03-interfacing-with-rest-apis-using-python/1.md
	modified:   labs/04-rest-04-coding-python-json/1.md
	modified:   labs/04-rest-04-coding-python-json/2.md
	modified:   labs/04-rest-04-learning-python-json/1.md
	modified:   labs/04-rest-04-learning-python-json/6.md
	modified:   labs/04-rest-05-mission/1.md
	modified:   labs/05-apic-03-apic-em-rest-api-python-app/1.md
	modified:   labs/05-apic-04-mission/1.md
	modified:   labs/06-dmi-01-introduction-to-standard-device-interfaces/lab.md
	modified:   labs/06-dmi-01-overview-of-device-level-netconf/1.md
	modified:   labs/06-dmi-01-overview-of-device-level-netconf/5.md
	modified:   labs/06-dmi-02-introducing-yang-data-modeling/4.md
	modified:   labs/06-dmi-02-introducing-yang-data-modeling/lab 2 - yang.md
	modified:   labs/06-dmi-02-yang-data-modeling-overview/4.md
	modified:   labs/06-dmi-02-yang-data-modeling-overview/5.md
	modified:   labs/06-dmi-02-yang-data-modeling-overview/7.md
	modified:   labs/06-dmi-03-using-restconf-to-interface-with-networking-devices/1.md
	modified:   labs/06-dmi-04-mission/1.md
	modified:   labs/06-dmi-04-mission/3.md
	modified:   labs/06-dmi-04-mission/4.md
	modified:   labs/06-dmi-05-mission/1.md
	modified:   labs/06-dmi-05-mission/4.md
	modified:   labs/07-virl-03-using-virl-test-apis/1.md
	modified:   labs/07-virl-04-mission/1.md
	modified:   labs/07-virl-04-mission/3.md
	modified:   labs/07-virl-04-mission/9.md
	modified:   labs/08-1-human-interaction-01-spark/1.md
	modified:   labs/08-human-interaction-01-spark-and-tropo/1.md
	modified:   labs/09-cmx-04-cmx-and-mse-mission-01/1.md
	modified:   labs/09-cmx-04-cmx-and-mse-mission-01/2.md
	modified:   labs/09-cmx-04-cmx-and-mse-mission-01/3.md
	modified:   labs/09-cmx-04-cmx-and-mse-mission-01/4.md
	modified:   labs/09-cmx-04-cmx-and-mse-mission-01/5.md
	modified:   labs/11-meraki-02-dashboard-api/1.md
	modified:   labs/11-meraki-03-click-through-captive-portal/1.md

**Comment by annegentle** [comment]
This has been done in the DNAv3 rewrite.
