### ISSUE TITLE
Participant Development Environment - Use of Git (LM-4002 and LM-1201)

### ISSUE THREAD

**Issue by cmlccie** [CiscoDevNet/devnet-express-dna-issues#23]
**Lab-Id:**  intro-python-programming-devnet-express

# Current use of Git in DNA Track:

- Presently we instruct participants to download the `devnet-express-code-samples` repo into a directory using the `git clone` command, and we tell them to use the `git pull` command to update.
- We provide instruction on using Git **after** they will have already used it (used in LM-4002 and instruction provided in LM-1201).
- We instruct them on the following commands:
![cisco_devnet_learning_labs](https://cloud.githubusercontent.com/assets/16244946/25145599/92505940-243f-11e7-9d30-50ae7ed1f9e7.png)

- We cover in our instruction:
   - Cloning a repo (which they have already used)
   - Using the `pull` command to 'update a repository' (which won't work for them after they modify a single file in the repository)

- We don't cover:
   - Creating and checking out a local branch with the `checkout command`
   - Saving your spot in your local branch with the `stash` command
   - Committing your work when you have successfully gotten your code working with the `commit` command
   - Updating the local repo with the `fetch` command

...which would make for a more beneficial DNE participant workflow.

# Recommendations
1. Remove the git lab, and simply have people `clone` the code as a download mechanism to get the code on their machine (simple but not instructive)
2. Setup the `devnet-express-code-samples` repo and provide instructions to enable a DNE participant's 'Git Workflow'

## Suggestions
- Store the sample code in the `main` branch
- Create a `solutions` branch  - To store the solutions to the exercises and missions (this could make it easier to keep the solutions up-to-date and if combined with https://github.com/CiscoDevNet/devnet-express-dna-issues/issues/24 could enable testing and validation of the solutions)
- Instruct the participants on how to create a local branch using either `git checkout -b` or `git branch`
- Instruct the participants on how to switch between branches using `git checkout`
- Instruct the participants on how to stash their changes before switching to a new branch using `git stash`, and how to commit their changes with the `commit` command once they have completed their exercise or mission and 'have working code'
- Instruct them on how to update the code in their local repository using the `git fetch` command

**Comment by brtiller1** [comment]
Bear in mind that our new path is to try to make these labs more generic so they can be used outside of DNE which is one reason for the repeated steps for downloading code as we don’t know from which lab users outside of DNE events will start and we want to avoid pushing them to other labs if a simple explanation can be given such as ‘clone this code here’s the command’ which is the typical case.  We already have Git labs that users can access to learn much more detail about Git.  In our DNE training Git is a very small piece and participants really only need to know the ‘clone’ and ‘pull’ commands.

If we don’t have a lab that clearly covers the Git commands suggested by Chris then one can be written and users can be referred to it for future learning.  But for our DNE training I don’t think spending much time training users on more  Git commands will be the best use of their time especially when they won’t be using these commands in the event for all other labs.

Brett

[http://www.cisco.com/web/europe/images/email/signature/logo05.jpg]

Brett Tiller
ENGINEER.CUSTOM APPLICATION
brtiller@cisco.com
Phone: +1 919 392 3307
DevNet
http://developer.cisco.com

Cisco Systems Limited
7025-6 Kit Creek Road PO Box 14987
RESEARCH TRIANGLE PARK
NORTH CAROLINA
27709-4987
US

**Comment by dstaudt** [comment]
Concur...labs should be reasonably self-contained - while balancing the 
need to avoid egregious repetition and redundancy to the extent possible 
(per  Chris' remarks.)

Regards,
- David Staudt

**Comment by annegentle** [comment]
I think we can consider this resolved with the various revisions we have in place now.
