### ISSUE TITLE
code bug 

### ISSUE THREAD

**Issue by bobg2015** [CiscoDevNet/devnet-express-dna-issues#3]
Hi,

There is a small typo at the following page for 'get_device_id' function definition with the headers assignment line.

[https://learninglabs.cisco.com/tracks/devnet-express-dna/devnet-express-np-rest-apic/05-apic-03-apic-em-rest-api-python-app/step/4](url)

`def get_device_id(token, url):

  #Define API Call
  api_call = "/network-device"

  #Header information
  headers = {X-AUTH-TOKEN" : token}
'

**Comment by brtiller1** [comment]
Fixed and committed to Repo.
