### ISSUE TITLE
09-cmx-01-introduction-to-cmx 'step 5' and all mission labs comments

### ISSUE THREAD

**Issue by yawming** [CiscoDevNet/devnet-express-dna-issues#32]
"Open the supplied code samples (TBD) and look through the various parameters that are used to setup the API call and **how the authentication occurs.**"
I think the goal in this lab is not to learn "how the authentication occurs" since we already asked the same in previous lab.

Over all these missions are not difficult for students to finish if we can provide code samples.
I did finish all exercises with the current scripts we have in repo.

**Comment by matthewjfarrell** [comment]
Ok, I'll finish the other code samples and update the instructions to point out the various methods used.  Thanks.

**Comment by matthewjfarrell** [comment]
Yawming, please review/close this issue.  I have made the changes to the pages where each code sample demonstrates something different and asks the student to take note of.  Please use the learning lab previewer or GitHub master for the changes.  Thanks, Matt

**Comment by yawming** [comment]
fixed
