### ISSUE TITLE
LM-4901 CMX Slides need review

### ISSUE THREAD

**Issue by austinMarcos** [CiscoDevNet/devnet-express-dna-issues#34]
In Spark room on April 18, Ruth wrote:

Please see email trail about the CMX module.  Matthew's revised slides are in the 'slides under development' folder: 
[https://cisco.box.com/s/at2s83fruaa4n8rqv9u0mt4skmkb8ftp](CMX LM-4901 Slides on Box)

Need to decide on timescale for releasing the new mission and slides. Suggest the end of this week to avoid confusing the Lima event.

**Comment by matthewjfarrell** [comment]
The second slide is an image but should be updated with new "Mission: Query the CMX API using Python scripts".  Does anyone have the components for creating a new image?

**Comment by RuthCattell** [comment]
@matthewjfarrell I'll do that.

**Comment by RuthCattell** [comment]
I've updated the slide deck with the new image.  Has @denapom11 seen this deck / seen the mission yet?  Are we ready to go live on Friday?

**Comment by matthewjfarrell** [comment]
Thanks Ruth, We are all set for moving learning labs to prod on Friday.  Matt

**Comment by denapom11** [comment]
Slides look good to me!  Let's rock and roll!

**Comment by denapom11** [comment]
New Mission is good too.  More accessible :)

**Comment by RuthCattell** [comment]
Release notes are still needed.  @austinMarcos - please provide them.  What then needs to happen about pushing the labs ... who gives the go-ahead?  Please advise.

**Comment by austinMarcos** [comment]
Slides have been published to:
https://cisco.app.box.com/files/0/f/22683757875/C_-_proposed_revisions_for_slides_post-v2
