### ISSUE TITLE
dCloud environment $PATH enhancement

### ISSUE THREAD

**Issue by mbrainar** [CiscoDevNet/devnet-express-dna-issues#35]
In LM-4002: Event Preparation for DevNet Express (for DNA) Step 4, I would recommend as an enhancement, having users execute the following command:
```
echo "export PATH=\"$PATH:/c/Program Files (x86)/Notepad++\"" >> ~/.bashrc && . ~/.bashrc
```
which will add Notepad++ to their path and enable them to launch notepad++ with the git bash terminal:
```
notepad++ filename.py &
```
Alternatively, it could be accomplished in the LM-4302: Verifying The Lab Environment module, or in each module before starting a lab.

**Comment by vvaliapa** [comment]
Fixed. Here is the updated Lab: https://developer.cisco.com/learning/lab/dnav3-verify/step/6
