### ISSUE TITLE
Release notes for the Post-Berlin Showstopper issues being released.

### ISSUE THREAD

**Issue by austinMarcos** [CiscoDevNet/devnet-express-dna-issues#36]
For the hosts of events, write up a list of changes being pushed.

**Comment by RuthCattell** [comment]
@austinMarcos - please provide these for CMX and for DNA (although it looks as if the DNA slides still need working on?  What's the status please?

**Comment by austinMarcos** [comment]
RELEASE NOTES

LM-4901 Labs and Mission
- The URL in the labs was updated to use the following sandbox: cmxlocationsandbox.cisco.com
- The Mission was re-written to use Python and to use the sandbox.
- renamed the folder in the code samples repo from Module09 to LM-4901

**Comment by RuthCattell** [comment]
Updated FINAL PUBLISH SLIDES folder for both LM-4901 and LM-4201 with the new slides, demo notes and a Release Notes box note.
https://cisco.box.com/s/pdlqz2sozox4tb4d0bavgji62vnf31n5

**Comment by austinMarcos** [comment]
Posted announcement in General Spark room to the DevNet Tiger Team.

**Comment by cmlccie** [comment]
Moved release notes to new `DevNet Express - Release Notes` folder:
