### ISSUE TITLE
Update CSR within Sandbox to IOS XE 16.5

### ISSUE THREAD

**Issue by hpreston** [CiscoDevNet/devnet-express-dna-issues#37]
At the next major update cycle, we should upgrade the code on the CSRs in the lab to version 16.5.  

This update will require changes to the Module 6 Labs due to YANG model changes.  
I have already identified these changes for the non-DNE Learning Labs so the work is fairly minimal.

If any other Module uses the CSR we should investigate the potential impact.

**Comment by klevenstein** [comment]
This issue is pretty old and has most likely been addressed in the updates to the DNAC DNE track. It's difficult to verify since the labs have changed significantly. Closing.
