### ISSUE TITLE
Folders in the code-samples repo should match the new labeling system of LM-xxxx

### ISSUE THREAD

**Issue by austinMarcos** [CiscoDevNet/devnet-express-dna-issues#38]
The current code samples repo uses folder names based on Module x labels:

https://github.com/CiscoDevNet/devnet-express-code-samples

Need to:
- change folder names to match the current module labels 
- change the paths in the labs to match the new folder names

**Comment by armartirosyan** [comment]
Folder have been renamed to meet the new naming convention. https://github.com/CiscoDevNet/devnet-express-code-samples

Text and screenshots have been updated to reflect the change
https://github.com/CiscoDevNet/devnet-express

**Comment by austinMarcos** [comment]
Changed the names for the labs and mission in the CMX module (to LM-4901). 

Published all labs to production.

**Comment by brtiller1** [comment]
Please fix issues below:
1.  Lab Python Primer Level 1 - Steps 2,3,4,5.  Directory text 'LM-4002' should be 'LM-1201'.  Assure that screens shots match text.
2. Lab Python Primer Level 2 - Steps 1-4.  Directory text 'LM-4002' should be 'LM-1201'. Assure that screens shots match text.
3. Corresponding slide decks need to updated for all with directory changes.

**Comment by austinMarcos** [comment]
Armen and I are going to look through the slides to make sure there are no incorrect references to the code samples. The slides that are being used in the upcoming events are here:

>https://cisco.app.box.com/files/0/f/22509384263/v2-DNA-slides

So far, I have verified that the following slide decks are clean:

- _H - LM-4602 - Device Level Interfaces - RESTCONF, NETCONF, and YANG.ppt_

**Comment by armartirosyan** [comment]
Below slides need to be changed to reflect new naming convention:
1. **G - LM-4502 - APIC-EM and REST APIs.pptx**
    * Slide 38
2. **F - LM-4402 - REST APIs.pptx**
    * Slide 26
    * Slide 33
3. **E - LM-1201 - Intro to Python and Programming Basics .pptx**
    * Slide 8
    * Slide 35
    * Slide 40

**Comment by austinMarcos** [comment]
Changes to slides can be made, delivered ASAP.

**Comment by armartirosyan** [comment]
All slides have been updated to reflect the folder name changes in devnet-express-code-samples repo

**Comment by austinMarcos** [comment]
The labs, pod v2.1, and the slides have all been updated to reflect the latest naming scheme of LM-nnnn.
