### ISSUE TITLE
Module LM-4002  - separate Windows/Linux/Mac instructions into separate labs

### ISSUE THREAD

**Issue by austinMarcos** [CiscoDevNet/devnet-express-dna-issues#4]

**Comment by securenetwrk** [comment]
I completely agree. It would be great if there were a way to choose a radio button, and only the relevant content shows for each step. That way the common content can be displayed for all, and variables like commands can just be filled in based on the selected radio button.

**Comment by cmlccie** [comment]
It appears that I created a duplicate issue... 🤕  Adding my input here.

We acknowledge five (5) different scenarios in which participants may be approaching this learning track using at least three (3) different platforms (Linux, Mac and Windows).  With fifteen (15) possible environments, clearly communicating what needs to be done, when and how is essential to participant success.

For the setup module, I believe segmentation of these scenarios and platforms would help provide the needed clarity and specificity, and as I see it you have at least a couple of options of how this could be accomplished by mapping the scenarios and platforms (in a matrix) to the `Learning Labs` and `Pages in a Learning Lab` constructs:

| ⬇ Platform & Scenario ➡ | # 1 | # 2 | # 3 | # 4 | # 5 |
| --- | --- | --- | --- | --- | --- |
| Linux | Instructions | ... | ... | ... | ... |
| Mac | ... | ... | ... | ... | ... |
| Windows | ... | ... | ... | ... | ... |

You could:

* Create a `Lab` for each scenario with a `Page` (in the lab) for each platform.
* Create a `Lab` for each platform with a `Page` for each scenario.

Using one of these methods would provide the needed separation (separating the instructions for each platform and scenario combination from the others), and (with the help of a little explanation and clean navigation) would provide very clear instructions for an individual participant as to what **they need to do** - in essence "this is the page for you... do everything on this page."

**Comment by austinMarcos** [comment]
Darien or Armen- When you make changes to LM-4002, please read the post at:
https://communities.cisco.com/message/252910

"I am going through the LM-4002: Event Preparation for DevNet Express (for DNA) module and on the Step 5 of that module I have an issue. When I open the AnyConnect secure mobility client (Version 3.2.09013) and paste the web address provided in the Step 5, I get a warning from the AnyConnect client telling me that untrusted VPN server had been blocked, and I'm not sure what should I do now. "

**Comment by hremond** [comment]
+1 on this enhancement. Finding the right content for the right platform proved to be sometime difficult for many attendees (DevNet Express for DNA - Lausanne)

**Comment by austinMarcos** [comment]
Based on conversation in scrum: @darien-hirotsu will publish updated labs to stage.

@cmlccie : please review the labs in stage for acceptance

**Comment by darien-hirotsu** [comment]
@cmlccie - Just a heads up, you can see this now in dev if you want to do a quick look over. 

https://github.com/CiscoDevNet/devnet-express/blob/master/labs/00-prep-01-prep-before-you-go/1.md

**Comment by darien-hirotsu** [comment]
@cmlccie - This is now posted to stage. If you have a few minutes to review and provide feedback, I can try to get this pushed to prod ASAP.

**Comment by austinMarcos** [comment]
Marcos recommended to push these updated labs to production on Monday, June 26. We want to make these available with the release of v2.2 (and the updated v2.2 pod).

**Comment by RuthCattell** [comment]
@austinMarcos Slide decks will also need to change. (LM 4002 and LM 4302).
As agreed, v2.2 pod going live on **Tues June 27** and starting to be used by events taking place from **Tues July 11**.  Events between June 27 and July 11 will need to use 2.1 material.

To ensure no confusion with event owners, suggested timeline is below:

**Tues June 27** - new pods available, 2.2 slide decks available, 2.2 labs **on stage**
**Monday July 10** - new pods used by all, 2.1 slides archived, 2.2 labs go live on prod replacing 2.1 labs.

Let's discuss tomorrow?

**Comment by RuthCattell** [comment]
What's the status on this?

**Comment by RuthCattell** [comment]
The go-live date was yesterday.  @austinMarcos - please advise the status.  Thanks.

**Comment by austinMarcos** [comment]
Delivered to production on July 10.
