### ISSUE TITLE
Release Notes for v2.2 - Updates to dCloud pod image and instructions

### ISSUE THREAD

**Issue by austinMarcos** [CiscoDevNet/devnet-express-dna-issues#43]
Need to summarize the changes being released with v2.2.

**Comment by austinMarcos** [comment]
@ecorban We are ready to roll out the dCloud pod image for the changes made to v2.2 of the track.

Eddie- When can we schedule the publishing of the pod? Can we do this during CLUS?

**Comment by ecorban** [comment]
hi marcos. talked with @armartirosyan. he has shared the pod and is testing with @yawming the changes to the pod (Cisco DevNet Express DNA Sandbox v2 Start:19-May-2017 16:30End:17-Jun-2017 16:30Session ID:401094Virtual Center:5Shared by:armartir). As soon as they give the ok to publish, we will begin the process.

**Comment by RuthCattell** [comment]
Status?

**Comment by yawming** [comment]
There are 6 labs, in the beginning of lab 1,3,5 says -  If you are installing the tools on your local machine for scenarios #1, or #3, you need to complete the steps on this page
Beginning of lab 2,4,6 says - If you are installing the dev tools on your local machine for scenarios #2, #4, or #5, you need to complete the steps on this page.

What are scenarios? Not mentioned.

1 Pre-Event Preparation for Windows Users Running Exercises on dCloud<https://learninglabs.cisco.com:8867/tracks/devnet-express-dna/00-pre-event-preparation/00-prep-01-prep-before-you-go-windows-dcloud/step/1>
2 Pre-Event Preparation for Windows Users Running Exercises on Local Hosts<https://learninglabs.cisco.com:8867/tracks/devnet-express-dna/00-pre-event-preparation/00-prep-01-prep-before-you-go-windows-host/step/2>
3 Pre-Event Preparation for Mac Users Running Exercises on dCloud<https://learninglabs.cisco.com:8867/tracks/devnet-express-dna/00-pre-event-preparation/00-prep-01-prep-before-you-go-mac-dcloud/step/1>
4 Pre-Event Preparation for Mac Users Running Exercises on Local Hosts<https://learninglabs.cisco.com:8867/tracks/devnet-express-dna/00-pre-event-preparation/00-prep-01-prep-before-you-go-mac-host/step/1>
5 Pre-Event Preparation for Linux Users Running Exercises on dCloud<https://learninglabs.cisco.com:8867/tracks/devnet-express-dna/00-pre-event-preparation/00-prep-01-prep-before-you-go-linux-dcloud/step/1>
6 Pre-Event Preparation for Linux Users Running Exercises on Local Hosts<https://learninglabs.cisco.com:8867/tracks/devnet-express-dna/00-pre-event-preparation/00-prep-01-prep-before-you-go-linux-host/step/1>

Other than this, steps in lab content is clear.

Thanks,

Yawming

**Comment by RuthCattell** [comment]
The go-live date for the Release Notes was yesterday.  @austinMarcos - please advise the status.  Thanks.

**Comment by austinMarcos** [comment]
**Release Notes for Event Hosts**

[Issue#4](https://github.com/CiscoDevNet/devnet-express-dna-issues/issues/4) **Module LM-4002** 
  - Labs: In v2 there was one lab that covered all scenarios. In v2.1 we broke the lab instructions into 6 labs, a different lab depending on which OS and dev environment combination the participant plans to use.
  - Slides: Removed the step numbers on slides that show lab steps for pre-event prep. Corrected module number in title of slide 16 to show correct module LM-4002.

[Issue#8](https://github.com/CiscoDevNet/devnet-express-dna-issues/issues/8) **Module LM-4201**
  - Labs: no changes
  - Slides: Updated the wording in the slides to reflect the changes we made to the demo. [box](https://cisco.box.com/s/pdlqz2sozox4tb4d0bavgji62vnf31n5)
  - Demo files: In v2 we included a demo to show how DNA might be used in a DevOps use case. In v2.1, we improved the scripting to set up the demo, and created a Docker container to make it easier to set up the demo in a classroom environment.

[Issue#17](https://github.com/CiscoDevNet/devnet-express-dna-issues/issues/17) **LM-4602**
  - Labs: Added text to the lab to describe how to invoke pyang from a Windows operating system in a command window.
  - Slides: no changes

[Issue#41](https://github.com/CiscoDevNet/devnet-express-dna-issues/issues/41) **Pod**
  - Labs: Updated all labs that show a path to the code samples directory in Github. In v2, the path included the words "ModuleN", In v2.1 we updated the labs to match the new folder structure in the code samples repo. In v2.1, the format for the directory names is "LM-nnnn".
  - Slides: Updated all slides that show a path to the code samples directory in Github. (Same as was done in the labs.)
  - Pod: 
     - Ubuntu workstation has more recent refresh of Github code samples: devnet-express-code-samples
     - Ubuntu workstation: removed .ngrok folder from main user's home directory (/home/cisco/) in order to fix occurrences of ngrok not running
     - Ubuntu workstation: updated bash script in rc.local to improve automatic update of Github code sample repo

[Issue#15](https://github.com/CiscoDevNet/devnet-express-dna-issues/issues/15) **Pod**
  - Labs: no changes
  - Slides: no changes
  - Pod: fixed problem of random intermittent APIC-EM crashes

[Issue#7](https://github.com/CiscoDevNet/devnet-express-dna-issues/issues/7) **Pod**
  - Labs: no changes
  - Slides: no changes
  - Pod: 
     - Ubuntu workstation: fixed file permissions to allow Github pull requests to code samples

**Comment by austinMarcos** [comment]
Published a summary of the notes on Box, in the folder that have the slides for v2.1:

> https://cisco.app.box.com/files/0/f/22509384263/v2.1-DNA-slides
