### ISSUE TITLE
Using the Location Services - notification listener ports issue

### ISSUE THREAD

**Issue by zapodeanu** [CiscoDevNet/devnet-express-dna-issues#44]
Here is the lab I mentioned: https://learninglabs.cisco.com/tracks/devnet-express-dna/dna-cmx-mse/09-cmx-03-cmx-and-mse-deep-dive/step/1
we will need multiple ports open for the listener. When I presented the session last week, I had only one port open.
It is frustrating for the attendees not be able to complete the lab.

**Comment by austinMarcos** [comment]
Gzby- I am looking again at this issue. I need to find a subject matter expert who can fix this. My goal is to resolve this by the end of August.

**Comment by gzapodea** [comment]
Marcos, Last time I presented the lab in Denver, 07/11-12 I had 100 ports available. I just tested for a random port (8099) in the range 8000-81000 and the port is still open on the notification listener server

**Comment by klevenstein** [comment]
CMX lab has been removed from the DNA Center DNE - closing.
