### ISSUE TITLE
Setup missing a step for dCloud reservation

### ISSUE THREAD

**Issue by austinMarcos** [CiscoDevNet/devnet-express-dna-issues#45]
The procedure on the following page is missing a step for reserving a dCloud pod. The dCloud interface requires the user to select a Data Center before they can see the catalog:

https://learninglabs.cisco.com/tracks/devnet-express-dna/devnet-express-lab-setup/03-environment-01-overview-of-the-lab-environment/step/2

**Comment by darien-hirotsu** [comment]
@austinMarcos This should be resolved. Feedback welcome.

https://github.com/CiscoDevNet/devnet-express/pull/107/commits

**Comment by austinMarcos** [comment]
Published on 31-July-2017. Marcos verified.
