### ISSUE TITLE
Room name not specified in instructions causing attendees making different rooms

### ISSUE THREAD

**Issue by tmero** [CiscoDevNet/devnet-express-dna-issues#46]
In these instructions, the room name should be the exact room the proctor provides for the event. When attendees complete this mission, the data gets posted to the Spark room. The proctor can track who completes the mission.

In the instructions, it doesn't mention this, causing everyone to create a different room, with the proctor not being able to see who completes the mission:

https://learninglabs.cisco.com/tracks/devnet-express-dna/dna-restconf-netconf-yang/06-dmi-05-mission/step/2

**Comment by darien-hirotsu** [comment]
@tmero This should be resolved and merged to dev. I added a comment clarifying where the Spark room should come from. Let me know if you have any feedback.

https://github.com/CiscoDevNet/devnet-express/commit/a64ff15669ede55dc3ac2a02419323344573c2d1

**Comment by austinMarcos** [comment]
Published on 31-July-2017. Marcos verified.
