### ISSUE TITLE
The "Hint" is not very clear for restconf pyang step 4

### ISSUE THREAD

**Issue by tmero** [CiscoDevNet/devnet-express-dna-issues#47]
After witnessing the attendees around me confused at this step, I think we should add a little more detail or at least a link to the pyang models and the expected behavior. This is only confusing to the less experienced people.

https://learninglabs.cisco.com/tracks/devnet-express-dna/dna-restconf-netconf-yang/06-dmi-05-mission/step/4

Content:
Hint
Use pyang to review the ietf-interfaces.yang model to find the names of the leafs. For a reminder on how to use the tool checkout Introduction to YANG Data Modeling Step 3

**Comment by darien-hirotsu** [comment]
@tmero I added a comment explaining that the expected output appears on the link and how to use it.

Let me know if you have any feedback!

**Comment by darien-hirotsu** [comment]
See the change here: https://github.com/CiscoDevNet/devnet-express/pull/105

**Comment by austinMarcos** [comment]
Published on 31-July-2017. Marcos verified.
