### ISSUE TITLE
"This is around line 90" is incorrect

### ISSUE THREAD

**Issue by tmero** [CiscoDevNet/devnet-express-dna-issues#48]
"This is around line 80". The function is being called on line 90. For the people brand new to Python, it is very confusing where to go. For people familiar with programming, it's obvious where to go. There needs to be a bit more clarification on how to make this change.

https://learninglabs.cisco.com/tracks/devnet-express-dna/dna-restconf-netconf-yang/06-dmi-05-mission/step/3

Content:
Within the function get_netconf(xml_filter) function, implement the correct NETCONF operation. This is around line 90.

**Comment by darien-hirotsu** [comment]
@tmero This should be resolved in dev. https://github.com/CiscoDevNet/devnet-express/pull/104/files

Feel free to review and provide additional feedback.

**Comment by austinMarcos** [comment]
Published on 31-July-2017. Marcos verified.
