### ISSUE TITLE
Introduction to NETCONF Slide - Needs minor clarification

### ISSUE THREAD

**Issue by tmero** [CiscoDevNet/devnet-express-dna-issues#49]
On the Introduction to NETCONF Slide, where it says "Lab #3: Introduction to NETCONF * Complete Step 7 - Querying for ietf-interfaces" The step 7 page says "Example 4", making attendees think they are not on Step 7 and they are on Step 4, feeling a bit lost. 

Can we add : " * Complete Step 7 - Querying for item-interfaces (Example 4) " to make it clear?

**Comment by armartirosyan** [comment]
The slide has been updated with suggested line.
https://cisco.box.com/s/7pivwjublrfyadkm655fj78qcnvxv9g9

**Comment by austinMarcos** [comment]
Verified the change in the slide. Released on 1-Aug-2017.
