### ISSUE TITLE
Wrong twitter handle on slides

### ISSUE THREAD

**Issue by securenetwrk** [CiscoDevNet/devnet-express-dna-issues#5]
The content all has an image telling us to tweet at @DevNet, but it should be @CiscoDevNet.

**Comment by cmlccie** [comment]
I created the templates, so this is my fault.  🤕

I'll work with Ruth to get these corrected.

**Comment by knightjoel** [comment]
Gentle reminder on this one: still an issue in v2.1 of the slides.

**Comment by annegentle** [comment]
Hi, thanks for circling back - I got the template Twitter handle fixed, @cmlccie let me know if I should check other published slide decks as well. Thanks!

**Comment by knightjoel** [comment]
Thanks @annegentle! 

We have an event coming up near the end of March. Do we need to wait for a new release of the decks? or can we get updated copies somehow from you in time for the event?

**Comment by knightjoel** [comment]
Hi @annegentle, just noticed that slide 44 in the deck for session 4502 still says '@devnet'. Also on that slide the social media icons are present but they don't hyperlink anywhere and don't have the handles/URLs beside them for devnet either.

**Comment by annegentle** [comment]
I've done a bunch of sampling and can't find any slides left with the wrong Twitter handle, so I'm closing this issue. Feel free to re-open if you find one to be fixed.
