### ISSUE TITLE
Step 1 is misleading and makes you think you need to complete those steps before going to Step 2

### ISSUE THREAD

**Issue by tmero** [CiscoDevNet/devnet-express-dna-issues#50]
It says to change all the things in the file. Then attendee gets stuck on certain parts, then realize the next few steps goes over them, but Step 1 gives the impression that it needs to all be completed prior to the next step.

https://learninglabs.cisco.com/tracks/devnet-express-dna/devnet-express-np-rest-apic/05-apic-04-mission/step/1 

suggestion made: Remove "Step 1" and keep the "Overall Guidelines".

**Comment by darien-hirotsu** [comment]
@tmero This should be resolved. I added an explanation clarifying the intent of the steps. Let me know if you have any other feedback/comments.

**Comment by austinMarcos** [comment]
Published on 31-July-2017. Marcos verified.
