### ISSUE TITLE
Need more time before starting the mission

### ISSUE THREAD

**Issue by tmero** [CiscoDevNet/devnet-express-dna-issues#51]
A lot of attendees didn't have time to work on this mission: 
https://learninglabs.cisco.com/tracks/devnet-express-dna/devnet-express-np-rest-apic/05-apic-04-mission/step/1

If we can get more time on this mission and less time on the prior labs, OR more time on the labs and less time on the mission, it could work out better :)

**Comment by annegentle** [comment]
This has been fixed with the revised dnav3 track.
