### ISSUE TITLE
Having Printouts of the Learning Labs

### ISSUE THREAD

**Issue by tmero** [CiscoDevNet/devnet-express-dna-issues#52]
Frequent feedback made to have a printout of the learning labs so you can easily go back to different steps/labs as a reference.

I'd personally recommend this as it's easier than having so many tabs open. When the content is foreign to you, it's more confusing moving to different pages.

**Comment by fracaen** [comment]
This has been requested by customer attendees in multiple cities.

**Comment by ObjectIsAdvantag** [comment]
I beleive this is something we arbitrated not to provide.
assigning to @annegentle to confirm and close issue

**Comment by annegentle** [comment]
Yes, no provision for PDF or printable copies of Learning Labs. Closing issue, thanks for mentioning it.
