### ISSUE TITLE
Remove Tropo from LM-4802: Interacting with Humans: DevOps Style

### ISSUE THREAD

**Issue by cmlccie** [CiscoDevNet/devnet-express-dna-issues#53]
Due to some positioning changes with Cisco Tropo, we should **remove the Tropo content** from the _LM-4802: Interacting with Humans: DevOps Style_ module.

Perhaps we could add some additional Spark content to supplement.  Very-basic bot?  SDK use?

**Comment by austinMarcos** [comment]
Next step is to assess the state of this work. Then communicate to Chris, Iftach, and Ruth to identify whether this impacts preparation for events.

**Comment by austinMarcos** [comment]
Labs updated and published on production server. Slides updated and pushed to [Box folder](https://cisco.box.com/s/pdlqz2sozox4tb4d0bavgji62vnf31n5) for presenters.

**Comment by austinMarcos** [comment]
Fixed and delivered to Box folder.
