### ISSUE TITLE
Meraki module for DNA track

### ISSUE THREAD

**Issue by RuthCattell** [CiscoDevNet/devnet-express-dna-issues#55]
Specification for a Meraki DNA module (led by Matt Denalpoli) is in the Box folder at https://cisco.box.com/s/egt8h3sjcb7mj93uqrx4phe6iwcyqzl1 and attached to this issue.
[meraki-dna-module-definition-june-2017.docx](https://github.com/CiscoDevNet/devnet-express-dna-issues/files/1098459/meraki-dna-module-definition-june-2017.docx)

email sent today to stakeholders (Colin and Dorothy from Meraki) asking for input.  If all is well, we wil go ahead with the attached.  Delivery timescale discussed between stakeholders = October 2017.

**Comment by darien-hirotsu** [comment]
@RuthCattell Looks like there is already an issue open for this (See issue42). I'll add your notes to the existing and close this redundant one.

https://github.com/CiscoDevNet/devnet-express-dna-issues/issues/42
