### ISSUE TITLE
wrong code in solution slide 30 - LM-4402

### ISSUE THREAD

**Issue by pseguel** [CiscoDevNet/devnet-express-dna-issues#56]
In slide 30, of LM-4402 it says:
for room in spark[" items"]:
	print("Title is: " + spark["title"] + ", type is: " + spark["type"])

It should be
for room in spark[" items"]:
	print("Title is: " + room["title"] + ", type is: " + room["type"])

**Comment by armartirosyan** [comment]
Slide 30 has been fixed. 
https://cisco.box.com/s/apg2p3ghdbh6gmjym2p9oqawk0s7s8po

**Comment by austinMarcos** [comment]
This issue has been fixed. See [https://cisco.app.box.com/files/0/f/22509384263/v2.1-DNA-slides_and_release_notes](release notes).
