### ISSUE TITLE
LM-4002 dCloud Pod Topology Incorrect

### ISSUE THREAD

**Issue by nschlutter** [CiscoDevNet/devnet-express-dna-issues#59]
The topology graphic indicates that the Windows Workstation IP is 198.18.133.36. The IP address is actually 198.18.133.36. This is on slide 7 of the LM-4002 deck. 

<img width="743" alt="screen shot 2017-08-15 at 11 08 58 am" src="https://user-images.githubusercontent.com/932716/29324769-ee3b549e-81aa-11e7-8db2-8d490f9759b2.png">

**Comment by armartirosyan** [comment]
Slide deck has been updated 

https://cisco.box.com/s/5jpsgp4tsa7nexu0url5m4kkww4iq68h

**Comment by austinMarcos** [comment]
@armartirosyan : I see the correction you made on the slide. Did you verify that IP address against the Pod?

**Comment by armartirosyan** [comment]
I did. I reserved a pod and made sure the IP is correct
![image](https://user-images.githubusercontent.com/7140657/29431420-b91c6afc-834c-11e7-9f28-01d5198af24a.png)

**Comment by austinMarcos** [comment]
Slides and labs updated. See latest slide in the [Box folder](https://cisco.box.com/s/pdlqz2sozox4tb4d0bavgji62vnf31n5) for presenters.
