### ISSUE TITLE
LM-4602 - discrepancy in mission counter types

### ISSUE THREAD

**Issue by securenetwrk** [CiscoDevNet/devnet-express-dna-issues#6]
In 01_get_interface_stats_SOLUTION.py it calls out the following: 

    message += "    * Packets In: %s \n" % (interface["statistics"]["in-pkts"]["#text"])
    message += "    * Packets Out: %s \n" % (interface["statistics"]["out-pkts"]["#text"])

However, running "pyang -f tree ietf-interfaces.yang" returns the following which doesn't list "in-pckts" as an option:
 ```
         +--ro statistics
             +--ro discontinuity-time    yang:date-and-time
             +--ro in-octets?            yang:counter64
             +--ro in-unicast-pkts?      yang:counter64
             +--ro in-broadcast-pkts?    yang:counter64
             +--ro in-multicast-pkts?    yang:counter64
             +--ro in-discards?          yang:counter32
             +--ro in-errors?            yang:counter32
             +--ro in-unknown-protos?    yang:counter32
             +--ro out-octets?           yang:counter64
             +--ro out-unicast-pkts?     yang:counter64
             +--ro out-broadcast-pkts?   yang:counter64
             +--ro out-multicast-pkts?   yang:counter64
             +--ro out-discards?         yang:counter32
             +--ro out-errors?           yang:counter32

```

The solution works, so my hunch is the yang file included in the github repo is out of sync with the version of router we are using.

**Comment by armartirosyan** [comment]
@securenetwrk - Looks like the code has been updated after this issues was created. Now, both python scripts don't have `message += "    * Packets In: %s \n" % (interface["statistics"]["in-pkts"]["#text"])`  and `message += "    * Packets Out: %s \n" % (interface["statistics"]["out-pkts"]["#text"])` lines. 

After successfully running the code user sees below message

```
## Interface Stats: Interface GigabitEthernet1
* Speed: 1000
* Status: up
* MAC Address: 00:50:56:b8:0c:97
* Statistics
    * Octets In: 7235
    * Octets Out: 377
    * Errors In: 0
    * Errors Out: 0


Mission Complete: Post to Spark Room
```

**Comment by austinMarcos** [comment]
Sample code fixed.
