### ISSUE TITLE
LM-4602 Data Model vs. Data Format Slide hard to read JSON

### ISSUE THREAD

**Issue by nschlutter** [CiscoDevNet/devnet-express-dna-issues#60]
The slide titled "Data Format Slide hard to read JSON" in the LM-4602 is hard to read. The JSON content on the left side is incredibly hard to read. I reformatted it to black and it is much easier to read.
<img width="1261" alt="screen shot 2017-08-16 at 2 08 56 pm" src="https://user-images.githubusercontent.com/932716/29380843-d22413a8-828c-11e7-8796-c40191689074.png">

**Comment by austinMarcos** [comment]
@jamesneimanconsulting s, can you please change the color to make the text more clear. The point of the slide is not to have students read the data. The actual data is inconsequential. The point of the slide is to show that a single data model can be expressed in multiple formats.  Just make the text more visible.

**Comment by jamesneimanconsulting** [comment]
@austinMarcos Here is the revised slide:
[H.-.LM-4602.-.Device.Level.Interfaces.-.RESTCONF.NETCONF.and.YANG.pptx](https://github.com/CiscoDevNet/devnet-express-dna-issues/files/1563307/H.-.LM-4602.-.Device.Level.Interfaces.-.RESTCONF.NETCONF.and.YANG.pptx)
