### ISSUE TITLE
dCloud pod allocation slides to be added to DNA deck

### ISSUE THREAD

**Issue by RuthCattell** [CiscoDevNet/devnet-express-dna-issues#63]
**Needed by Friday Oct 6.**

For the DNA events, the new Broker process for taking attendees through how to access their dCloud pods needs to be included within the [Verifying the Lab Environment slide deck](https://cisco.box.com/s/r86zknfhrwenx73e3e2e3gse2dr84z7t), with the old information removed.

Also, the old dCloud allocation process is also mentioned in the [Event Prep slide deck](https://cisco.box.com/s/5jpsgp4tsa7nexu0url5m4kkww4iq68h).  This needs to be removed or the new info inserted.

In the final **DCI** [Welcome and Prep] (https://cisco.box.com/s/lyz563jryj3ub04uzxysvvj5h95jtb7k) slide deck I have inserted the 'broker allocation' slides presented by @cmlccie for the virtual T-the-T session.  You can presumably use those 2/3 slides in the DNA decks mentioned above.

**Comment by austinMarcos** [comment]
Talked to Ruth. Will make these changes ASAP, and verify that the process agrees with info published on Jive:
> https://cisco.jiveon.com/docs/DOC-1855206

**Comment by RuthCattell** [comment]
Has this been done yet please?  2 DNA events this week: one starting today and the other tomorrow.  They need the slides.  Thanks.

**Comment by klevenstein** [comment]
Closing this as it's nearly 18 months old and the events are long past; reopen if needed.
