### ISSUE TITLE
Overhaul of Programming Basics Primer content

### ISSUE THREAD

**Issue by annegentle** [CiscoDevNet/devnet-express-dna-issues#65]
When delivering DevNet Express content, trainers have discovered a need to reset the foundation in Python, APIs and Data Formats written up in Learning Labs for delivery as Tracks (with Modules).

**Comment by annegentle** [comment]
These are the two team's reports from content analysis so far:
Programming Fundamentals outline (from Hank's recent work at https://cisco.app.box.com/folder/34827797838):
Data Formats - Understanding and using JSON XML and YAML
APIs are Everywhere - What are they?
REST APIs Part 1 - HTTP is for more than web browsing
REST APIs Part 2 - Making REST API Calls with Postman
Python Part 1 Python Language and Script Basics
Python Part 2 Working with Libraries and Virtual Environments
Python Part 3 Useful Python Libraries for Network Engineers

Learning Content Outline (from Consolidated Primer Feedback at https://cisco.app.box.com/notes/245578106389):
Python Primer Part 1 - Python interpreter, virtual environments, IDLE/Bash, data types, variables, operations, conditionals
Python Primer Part 2 - Python objects, libraries, structures, loops, functions, basic debugging
Rest APIs - Getting started, client (Postman), parsing JSON with Python

**Comment by annegentle** [comment]
These are the existing collection of tracks and modules today: 

 Primer Content as it exists today:
[DNA Track](https://learninglabs.cisco.com/tracks/devnet-express-dna):
LM-4002: Event Preparation for DevNet Express for DNA v2.1
LM-1201: Intro To Python and Programming Basics for DevNet Express
LM-4402: REST APIs
[Cloud Collaboration Track](https://learninglabs.cisco.com/tracks/devnet-express-cloud-collab-it-pro):
Pre-Event Preparation for IT Pros
Python Programming Basics for Cloud Collab IT Pros
[Data Center Infrastructure](https://learninglabs.cisco.com/tracks/devnet-express-dci):
LM-5001 - Pre-event information
LM-1221: Intro To Git, Python, XML and Programming Basics for DevNet Express
LM-4402: REST APIs

What we're working on next is whether these current pieces (tracks, modules, and labs) can be edited as-is or do we need completely new tracks? New Modules? New Labs too?

**Comment by annegentle** [comment]
This is a first-pass through the repos that would need to change to update labs. However, I'm not sure if editing those repos gives the deliverable we want, which is a new outline. Posting here for an idea of sizing.

_LM-1201_
Introduction to Git
Repo: https://github.com/CiscoDevNet/devnet-express-cloud-collab (private)

Python Primer Level 1
Repo: https://github.com/CiscoDevNet/devnet-express (private)

Python Primer Level 2
Repo: https://github.com/CiscoDevNet/devnet-express (private)

Parsing JSON with Python
https://github.com/CiscoDevNet/devnet-express (private)

_LM-4002_
Pre-Event Preparation for Windows Users Running Exercises on dCloud
Repo: https://github.com/CiscoDevNet/devnet-express (private)

Pre-Event Preparation for Windows Users Running Exercises on Local Hosts
Repo: https://github.com/CiscoDevNet/devnet-express (private)

Pre-Event Preparation for Mac Users Running Exercises on dCloud
Repo: https://github.com/CiscoDevNet/devnet-express (private)

Pre-Event Preparation for Mac Users Running Exercises on Local Hosts
Repo: https://github.com/CiscoDevNet/devnet-express (private)

Pre-Event Preparation for Linux Users Running Exercises on dCloud
Repo: https://github.com/CiscoDevNet/devnet-express (private)

Pre-Event Preparation for Linux Users Running Exercises on Local Hosts
Repo: https://github.com/CiscoDevNet/devnet-express (private)

_LM-1221_
Introduction to Git
Repo: https://github.com/CiscoDevNet/devnet-express-cloud-collab (private)

Python Primer Level 1
Repo: https://github.com/CiscoDevNet/api-coding-basics (private)

Python Primer Level 2
Repo: https://github.com/CiscoDevNet/api-coding-basics (private)

Using Python to Parse JSON
Repo: https://github.com/CiscoDevNet/api-coding-basics (private)

Introduction to XML
Repo: https://github.com/CiscoDevNet/api-coding-basics (private)

# LM-4402
Overview of REST APIs
Repo: https://github.com/CiscoDevNet/devnet-express (private)

Spark's REST API and Postman
Repo: https://github.com/CiscoDevNet/devnet-express (private)

Using Python to Interface with REST APIs
Repo: https://github.com/CiscoDevNet/devnet-express (private)

Coding and Parsing with Python
Repo: https://github.com/CiscoDevNet/devnet-express (private)

Mission: Complete the Spark Script with Python
Repo: https://github.com/CiscoDevNet/devnet-express (private)

**Comment by annegentle** [comment]
Ok, one more set of input, the Dec 2017 NetAcad training event:
Day 1:
An introduction to APIs and APIC-EM
Making API calls in Postman
Introduction to Git
Introduction to coding in Python
Coding in Python for APIC-EM
Day 2:
Cisco Meraki Integrations 
Cisco Spark Integrations 
Cisco Network Programmability with NetConf/RESTConf 
Cisco Security - Cisco Firepower Management Center platform and Cisco AMP Cloud

**Comment by annegentle** [comment]
In this revision: 

Phase 1:
Set up basic naming conventions and folder conventions. BUT do not break others and keep the labs we have. 
Anne - Go through Issues already reported and see if they are fixed in source and published in output.
Anne - Fix Issues in dna-express that are not fixed (that do not also break other labs using a specific desktop image, such as if folder structure is changed).
Anne - Use better code samples that are more about networking than generic.

Phase 2:
Convert screenshots that are code to text with backticks in markdown. Chris - rally some resources to fix the screenshots. Anne to merge quickly on the days you sprint on this.
Updates across more of the tracks with folder structure we want.

**Comment by annegentle** [comment]
@austinMarcos Would love your input on these comparisons as you coordinate the collaboration. Let us know your thoughts.

**Comment by annegentle** [comment]
Outline for revisions for review by @hpreston, @aroach, @cmlccie.

What gets removed from the module: 
* Introduction to Git
* All Pre-Event Preparation labs

What gets added: 
Make all examples more network-centric.

Outline: 

1. Data Formats - Understanding and using JSON XML and YAML
2. APIs are Everywhere - What are they?
3. REST APIs Part 1 - HTTP is for more than web browsing
4. REST APIs Part 2 - Making REST API Calls with Postman, parsing JSON with Python
5. Python Part 1 Python Language, Python interpreter, IDLE/Bash, and Script Basics
6. Python Part 2 Working with libraries, virtual environments, data types, variables, operations, conditionals
7. Python Part 3 Useful Python libraries for Network Engineers, Python structures, loops, functions, basic debugging

**Comment by cmlccie** [comment]
My feedback:

**Order:**  (I would recommend the following grouping and ordering of the content.)
1. Python Part 1 - A Basic Python Development Environment
  1. Bash
  1. Python Interpreter
  1. IDLE
  1. Script Basics
  1. Working with Libraries
  1. Virtual Environments
1. Python Part 2 - Python Language
  1. Basic Data Types
  1. Variables
  1. Operations
  1. Conditionals
1. Python Part 3
  1. ~~Useful Python libraries for Network Engineers~~ (Move to a reference-able "Awesome" list?)
  1. Container Data Types
  1. Loops
  1. Functions
  1. Basic Debugging
1. Data Formats - Understanding and using (atomic and plug-able - include as needed per module/track)
  1. JSON
  1. XML
  1. YAML
1. API Introduction
  1. REST APIs Part 1 - HTTP is for more than Web Browsing
  1. REST APIs Part 2 - Making REST API Calls with Postman -> Moving to Code

**Comment by annegentle** [comment]
Thanks @cmlccie -- I'm revising with more detail about module and lab levels as well and will incorporate in the comment above.

**Comment by annegentle** [comment]
Summary proposal:

## 1. Revise Intro to Git - Chris and Anne
*Repo*: https://github.com/CiscoDevNet/devnet-express-cloud-collab (private)
Step1: Intro to Git
Step2: Getting Source Code Files with git clone
Step3: Updating a Local Repository with git pull (@cmlccie to revise for workflow with git clone, git checkout, git pull, git commit, and so on, addressing issues from https://ahorribleprogrammer.wordpress.com/2017/06/16/my-thoughts-on-cisco-devnet-beginner-fundamentals-module/)

## 2. Revise Intro to REST API - Anne
*Repo*: https://github.com/CiscoDevNet/devnet-express (private)
New topics:
What is REST? - Use for the HTTP protocol, REpresentational State Transfer
A Look Under the Hood at REST - URI (endpoints), resources, parameters, headers, auth, data
was:Overview of APIs
Some REST Examples - Chuck Norris database and Spark API was:Step 1. Get Access To The Spark REST APIs (Change to show Chuck Norris example and then a Spark API example)
was:Step 2. What is a REST web service?
New topic: Payloads - JSON, XML
Getting Started with an API - Docs, Auth, Endpoints, Verbs, Parameters, Payloads
was:Step 3. The Anatomy of a REST API Request
REST API Tools - curl, Postman, Requests Python library, Swagger/OpenAPI for Dynamic API
Documentation, Browser Developer Tools was:Step 4. Use Postman to Call the Spark API
CRUD REST Verbs - Post Get Put Delete
## 3. Hank, Ashley, Matt review all Pull Requests for the new changes and guide as needed.
## 4. Revise Python 1, 2, add 3? - Get agreement on topics, find an owner/author. Anne can test and review as needed.

**Comment by annegentle** [comment]
Status update: 
* Update to Python Primer I completed in [intro-to-programming](https://github.com/CiscoDevNet/intro-to-programming/tree/master/labs/intro-to-python-primer-1).
* New Intro to REST API completed in new [repo](https://github.com/CiscoDevNet/rest-api-learning-labs).

**Comment by annegentle** [comment]
Closing issue as the reviews are ongoing in email and in preparation for the content sprint.
