### ISSUE TITLE
dcloud workstation - file permissions

### ISSUE THREAD

**Issue by securenetwrk** [CiscoDevNet/devnet-express-dna-issues#7]
On the dcloud linux workstations, users encountered a number of file permissions issues on the pre-downloaded github files. Random files were owned by root and lacked rw permissions. We should either instruct users to "sudo chmod -R 777 ." the entire folder or try to fix the upstream image to have consistent permissions. Or, have users clone the repo themselves.

**Comment by austinMarcos** [comment]
Discussed in Friday triage meeting: because the pod image has a version of the repo that is significantly diverged, we need to:

- fix the pod image (CiscoDevNet/devnet-express-dna-issues/issues/41)
- temp workaround: add instructions to the lab to get the latest repo (using git reset)

**Comment by austinMarcos** [comment]
Let's publish ASAP (after coordinating with Ruth on best time to push).

Write the new instructions into the preparation module.

**Comment by armartirosyan** [comment]
Event Preparation for DevNet Express lab was updated with below instructions as a temp workaround.
> **IMPORTANT:** Unfortunately, Ubuntu host has some issues with code samples directory. This issue will be resolved in future updates, meanwhile, if you choose to use the node, please follow below steps to fix your local copy:
>  * Open LXTerminal and navigate to `Code` directory: `cd /home/cisco/Code`
>  * Remove current code samples folder: `sudo rm -r devnet-express-code-samples` use password **C1sco12345** for sudo.
>  * Clone the `devnet-express-code-samples` repository from github: `git clone https://www.github.com/CiscoDevNet/devnet-express-code-samples.git`

**Comment by austinMarcos** [comment]
The pod image needs to be updated by Eddie to get the repo to synch seamlessly.

**Comment by austinMarcos** [comment]
@austinMarcos Next need to:
- verify that this workaround instruction is edited and 
- published.

**Comment by austinMarcos** [comment]
See resolution (updated pod image): CiscoDevNet/devnet-express-dna-issues/issues/41

Closing this issue as duplicate.
