### ISSUE TITLE
LM-1201: ctrl+z to quit

### ISSUE THREAD

**Issue by knightjoel** [CiscoDevNet/devnet-express-dna-issues#71]
In the v2.1 slides for LM-1201 (Intro to Python), slide 13, the instructions for exiting Python suggest using "Ctrl Z". That keystroke doesn't exit Python, it only suspends it into the background which can lead to confusion for students as to why they end up with multiple Python processes running in the background. 

The correct keystroke should be "Ctrl D". This actually exits Python.

```
~% python
Python 2.7.10 (default, Jul 15 2017, 17:16:57)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>  <type Ctrl+Z>
[1]  + 46128 suspended  python
~%
```

```
~% python
Python 2.7.10 (default, Jul 15 2017, 17:16:57)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> ^D
~%
```

**Comment by annegentle** [comment]
Hoping @austinMarcos can take a look while he's updating these slides.

**Comment by klevenstein** [comment]
Fixed in the latest revision of the DNE; closing
