### ISSUE TITLE
Presenter decks: broken social icons

### ISSUE THREAD

**Issue by knightjoel** [CiscoDevNet/devnet-express-dna-issues#72]
Hi.

Looking through the v2.1 presenter decks, I see that on two of the very last slides, it looks like there should be some icons for social networks (LinkedIn, Twitter, Github). Those icons are showing up as "?" question marks when I view the slides in PowerPoint and also in Box.com's HTML interface.

My system:
- OS X 10.13.3
- MS Office 2016 (16.10)

I imagine this is probably related to something on my system or something missing from my system that should be here (a font perhaps?). I'm more than happy to help test different things so that the slides can be fixed and/or instructions can be created for presenters so they don't run into this as well.

<img width="585" alt="screen shot 2018-03-06 at 15 55 34 copy_resized" src="https://user-images.githubusercontent.com/17298529/37063505-da6dbae6-2156-11e8-9cfc-676709da2919.png">

<img width="1066" alt="screen shot 2018-03-06 at 15 55 40" src="https://user-images.githubusercontent.com/17298529/37063510-e0026308-2156-11e8-8fa6-28727014aa18.png">

**Comment by knightjoel** [comment]
On a suggestion from @cmlccie I did install Fontawesome but did not notice any change after closing/opening PowerPoint. Tried FA v5 and v4.

**Comment by annegentle** [comment]
I see the same in the template, and I'm on the same system as you, though my PowerPoint is version 16.9 (and the updater didn't say I could get another version). I also tried to install Font Awesome and no luck. I tried the techniques listed in https://github.com/FortAwesome/Font-Awesome/issues/7205#issuecomment-131164500 and still no luck. Is a good way forward is to use images? This seems to be a common problem.

**Comment by knightjoel** [comment]
I was talking with Ruth Cattell in Spark, letting her know I had created this issue, and she mentioned that she thought everything should be using Arial. She also said she would attempt to find time today/tomorrow to investigate.

**Comment by RuthCattell** [comment]
Can you see the icons now in this version: https://cisco.box.com/s/5f1r9n7kqk38qpp3tmj5pqys8indhqw4
If so, I'll replace that page on the other decks and also add the logos to the DevNet | DevNetExpress slide too.  I think they weren't showing because of they way they'd been inserted (ie copied and pasted as opposed to inserted).

**Comment by annegentle** [comment]
Great, thanks Ruth! Screenshot: 
<img width="746" alt="screen shot 2018-03-08 at 9 35 12 am" src="https://user-images.githubusercontent.com/501981/37159684-103990ec-22b4-11e8-8493-37c05d206467.png">
I went ahead and changed the master slides as well, there were four slides where these icons are needed.

**Comment by RuthCattell** [comment]
Thanks @annegentle.  The template isn't used by the SEs - it's just there for my benefit.  So, I need to go in and change the master on all of the slide decks.  The SEs just copy them over to their folder, personalise them, and use them.  Will do this by end of tomorrow (using the slides you updated in the template).

**Comment by RuthCattell** [comment]
@annegentle I now see what you mean: you've updated the other 3 slides in that deck.  Great - thanks!  I'll go and update the other slide decks now.  Thank you.

**Comment by knightjoel** [comment]
thanks @annegentle!

**Comment by RuthCattell** [comment]
@knightjoel - I've updated all 11 slide decks with the 3 icons on the appropriate slides. @annegentle

**Comment by annegentle** [comment]
Thanks, closing Issue.
