### ISSUE TITLE
Missing "pip install xmltodict" for NetConf module

### ISSUE THREAD

**Issue by rbochciscocom** [CiscoDevNet/devnet-express-dna-issues#74]
When attendee follows "environment setup" instructions and then go to "Exploring IOS XE YANG Data Models with NETCONF" and reach the module "Step 3: Walking through automating your network with NETCONF", he is receiving the error, basically saying that "xmltodict is not available to import". So we should state somewhere withit this step (https://learninglabs.cisco.com/tracks/dnav3-track/dnav3-intro-mdp/dnav3-intro-netconf/step/4) or in environment setup that "pip install xmltodict" is needed.

**Comment by annegentle** [comment]
We'll fix it in the code repo, with the `requirements.txt` file. See https://github.com/CiscoDevNet/dnav3-code/pull/24

**Comment by hpreston** [comment]
I've merged this in.
