### ISSUE TITLE
DNA Center lab

### ISSUE THREAD

**Issue by darktech666** [CiscoDevNet/devnet-express-dna-issues#75]
Some feedback on the DNA Center lab section.
The mission is not appropriate for DNAC. DNAC is already providing a tool for topology, and doing a lab that you have to code and use another tool to create a topology can be misleading for customers who are new to DNAC. It can leave them the impression it's complicate to use the platform and you have to "script" to achieve result like this. We need to find a better mission more in line with DNACaaP to show the power of DNAC.

Also the python code provided in the lab is to complex or I should say to much optimize. The day prior we are doing an introduction to python for beginner and in this lab we are jumping to complex python code with a lot of call to function. Example, folks are new to REST URL API call, so to better understand, they should not see the get_url function, they should see instead the full URL on one line to better understand. I know it's not optimize in term of code, but at least is will be easier to get started in more complex code.

Thanks

Martin

**Comment by klevenstein** [comment]
The DNA Center lab has been revised and updated - closing.
