### ISSUE TITLE
Hands on lab part2

### ISSUE THREAD

**Issue by rapellos** [CiscoDevNet/devnet-express-dna-issues#76]
I noticed that in the sample solution to **Part 2 hands-Ob lab**,  _fortune-cookies.py_, the "raise NotImplementedError" was omitted. I have included it in mine inside a try - except loop. Is this fine and legal? I have no errors when I run the code. Thanks 
_try:
        return ("Your lucky number(s): {} \nYour fortune: {}\n\n" .format(number, fortune))
except:
        raise NotImplementedError()_

**Comment by klevenstein** [comment]
DNA DNE track has been updated; closing.
