### ISSUE TITLE
Track description is inconsistent with DevNet Express track descriptions

### ISSUE THREAD

**Issue by RuthCattell** [CiscoDevNet/devnet-express-dna-issues#77]
Please change to make it clear that this is a DNE and therefore the modules are to be consumed at a DevNet Express.  Change to read:

This track contains the modules and labs taught at a DevNet Express event: where you listen, learn, and then put your new knowledge into practice. Learn about automation, operational scripting, DevOps integration points, and app development on top of your DNA network. Looking to dive into the world of programming your enterprise network? Curious about the APIs for "Cisco DNA"? Well, then this DevNet Express Learning Track is for you.

**Comment by annegentle** [comment]
Done - see https://learninglabs.cisco.com/tracks/dnav3-track
