### ISSUE TITLE
remove 'beta' references from https://learninglabs.cisco.com/tracks/devnet-express-dna

### ISSUE THREAD

**Issue by RuthCattell** [CiscoDevNet/devnet-express-dna-issues#79]
Remove 'beta' from the individual modules and overall track description.

**Comment by annegentle** [comment]
Do you mean that the staging link should not be marked beta? Or do you mean the production link should not be marked beta?

**Comment by RuthCattell** [comment]
There should be no reference to 'beta' on the production site.

**Comment by annegentle** [comment]
Ok, updated the title to remove the port value for staging.

**Comment by annegentle** [comment]
Cleared "beta" on production - closing.Thanks for reporting!
