### ISSUE TITLE
LM-4201: Demo for DNA Explained - Add a container environment

### ISSUE THREAD

**Issue by austinMarcos** [CiscoDevNet/devnet-express-dna-issues#8]
Enhancement:  put the scripts for the demo in a Docker container so that it is easier to launch and more predictable in different hosting environments.

- will require docker to be installed on the event hosts' local machine
- will help to reduce need to install all the libraries needed to run the demo
- needs to be able to run concurrent sessions (for when there are multiple events at the same time)

Use Spark room that Chris L. to share review of the updated demo.

**Comment by RuthCattell** [comment]
Is there an update on this?

**Comment by austinMarcos** [comment]
Verified that the demo scripts are in the [code samples repo](https://github.com/CiscoDevNet/devnet-express-code-samples).

**Comment by RuthCattell** [comment]
Updated FINAL PUBLISHED SLIDES folder for LM-4201 with new slides, demo notes and a Release Notes box note.
https://cisco.box.com/s/pdlqz2sozox4tb4d0bavgji62vnf31n5

**Comment by austinMarcos** [comment]
Armen delivered container environment. Published and ready for use.

**Comment by cmlccie** [comment]
We need to create an editable / re-creatable container environment via a Dockerfile.  I am working with @armartirosyan on this.

**Comment by robertcsapo** [comment]
Supports Kitematic (ports, volume and /bin/bash shell)
pip install could be better automated if repository was maintained with a general requirements.txt

```
FROM python:3

RUN DEBIAN_FRONTEND=noninteractive pip install \
virtualenv \
requests \
cryptography==1.2.1 \
ncclient \
netaddr \
argparse \
pyang \
enum34 \
ipaddress \
wheel

ENV SHELL=/bin/bash
WORKDIR /root/
RUN DEBIAN_FRONTEND=noninteractive apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install telnet vim nano -y
RUN DEBIAN_FRONTEND=noninteractive git clone https://github.com/CiscoDevNet/devnet-express-code-samples.git
WORKDIR /root/devnet-express-code-samples/
VOLUME /root/devnet-express-code-samples/localfolder/
CMD /bin/bash
```

**Comment by cmlccie** [comment]
@robertcsapo Thanks for sharing your DockerFile; however, what we are talking about in this issue is a building a cleanly executable image for hosting the DNA Explained ChatOps demo bot.

**Comment by cmlccie** [comment]
@armartirosyan I finished building the image automation tools to make the image creation and maintenance a little more streamlined:
* `requirements.txt` - Streamlines the installation of the Python package dependencies
* `docker_launch_bot.sh` - Streamlines the bot startup process
* `Dockerfile` - Automates the image build process
* `docker-compose.yml` - Streamlines the container creation process
* `Makefile` - Convenience file for executing the relevant commands in the build process

Please feel free to check out the sources and test built image before I submit a pull request:
* Source - [cmlccie/cmlccie/devnet-express-code-samples - iss08-issues-repo Branch](https://github.com/cmlccie/devnet-express-code-samples/tree/iss08-issues-repo/LM-4201)
* Built Test Image - [cmlccie/dna-explained-demobot](https://hub.docker.com/r/cmlccie/dna-explained-demobot/)

**Comment by cmlccie** [comment]
You can easily try out the image with the following command:
``` bash
docker run -it --rm --privileged --name demobot cmlccie/dna-explained-demobot:latest
```

**Comment by austinMarcos** [comment]
@armartirosyan and @yawming should at minimum talk about this process of delivering a container.  If Yaming can access the resources, he should test it.  Otherwise, if all seems to be working Armen or Yawming can mark this as done once delivered.

**Comment by armartirosyan** [comment]
@cmlccieI made couple of changes in Dockerfile and demo_bot.py file so the ngrok and chatbot can be accessed from the host.  PR https://github.com/cmlccie/devnet-express-code-samples/pull/1
Also, I updated the docker image with latest changes.
After @yawming is done with QA we can go ahead and create a pull request and merge the changes with the master branch.

Thanks

**Comment by cmlccie** [comment]
Changes look great @armartirosyan !  I merged the pull and made one following commit (changing home-relative paths to absolute paths - just for consistency).

The instructions document may need to be updated, but otherwise the container image should be ready for QA.

**Comment by armartirosyan** [comment]
Instructions document has been updated to reflect the changes made to the docker image.

**Comment by cmlccie** [comment]
Thanks @armartirosyan !  I like the inclusion of the Table of Contents.

I do note that we are referring / using the Docker image posted under my GitHub account (`cmlccie/dna-explained-demobot`), which I don't mind, but I'm not sure that is the best place for it.

Does DevNet have an "organization" setup on DockerHub - like they do with `CiscoDevNet` on GitHub?  If not, we should probably get one setup there and post 'published images' there instead of underneath individual account names.  Doing so will help with maintaining these images, and keep all of the images 'in one place.'

**Comment by yawming** [comment]
1.  I agree with Chris that maybe post Docker image under DevNet github
2. I followed through the document - https://cisco.app.box.com/files/0/f/22683757875/1/f_166467429614 starting from page 5 - Instructions for the Demo in Docker Container.
It worked as expected but I have a concern about the continuity.

This section ended with “If everything was entered correctly, the last line printed by the script should state that bot is running on http://0.0.0.0:8080/”
Then there is a page of blank after that start with “Instructions on How to Use the Demo Bot” following with


1.       On your host machine, use Cisco AnyConnect to connect to the dCloud.
The URL and necessary credentials can be found in the pod’s details page.


So if I am totally new here I will ask what is this Instructions for the Demo in Docker Container about? At least we can explain after “If everything was entered correctly, the last line printed by the script should state that bot is running on http://0.0.0.0:8080/” when, where and how  we will use it

**Comment by austinMarcos** [comment]
Based on scrum conversation, is this enough support?  At what point do we stop explaining how to setup the Docker environment?  
Yawming suggested that we make it more clear where to go in the next step from this option (the option of using the Docker file versus the Ubuntu host).  In other words, recommend more clarity on next steps.

**Comment by RuthCattell** [comment]
Status?

**Comment by austinMarcos** [comment]
The Docker container and instructions have been delivered.
