### ISSUE TITLE
Code example is wrong

### ISSUE THREAD

**Issue by swiatecki** [CiscoDevNet/devnet-express-dna-issues#80]
On page https://learninglabs.cisco.com/tracks/dnav3-track/dnav3-intro-dnac/dnav3-dnac-nbapi-hello-world/step/6 

Under **Complete Python script**. 

The line `if name == "main":` should be `if __name__ == "__main__":`

**Comment by klevenstein** [comment]
Check to make sure this is addressed in DNA DNE v4

**Comment by klevenstein** [comment]
fixed in DNAC DNE v4, closing
