### ISSUE TITLE
Missing expected and sample output in instructions.

### ISSUE THREAD

**Issue by tnothnag** [CiscoDevNet/devnet-express-dna-issues#81]
Hi team,

there are some 'expected' and 'sample' output missing on this page.
https://learninglabs.cisco.com/tracks/dnav3-track/intro-ansible-iosxe/ansible-ios-modules/step/2
![image](https://user-images.githubusercontent.com/29453904/49406906-29c82c80-f757-11e8-8e29-a4628c381c97.png)

**Comment by annegentle** [comment]
HI, can you let us know the browser, version, and operating system you see this on? You should see a small triangle next to "Expected" like the screenshot below. Most browsers support it but we'll have to see what is different about your browser.

<img width="956" alt="screen shot 2018-12-03 at 5 21 01 pm" src="https://user-images.githubusercontent.com/501981/49407929-f1592c00-f71f-11e8-8290-285de2a7d20c.png">

**Comment by tnothnag** [comment]
Hi,

I am on Firefox 63.03 and on Mac OSx 10.13.6.

Indeed! If I click on ‘expected output’, I can see it. The mouse pointer does not indicate that there is something hidden (in case that is intended).

Regards,
Tim

**Comment by tnothnag** [comment]
Just FYI: With Safari 12.0.1 I can see the small triangle next to ‘Expected’.

Regards,

Tim
