### ISSUE TITLE
Typo in question - Ansible IOS native modules

### ISSUE THREAD

**Issue by tnothnag** [CiscoDevNet/devnet-express-dna-issues#82]
Hi team,

https://learninglabs.cisco.com/tracks/dnav3-track/intro-ansible-iosxe/ansible-ios-modules/step/4

The question is:  Can you identify which module was used to configure NTP on the server?

IMO, the question should be: Can you identify which module was used to configure the Loopback interfaces on the routers?

![image](https://user-images.githubusercontent.com/29453904/49407765-faff8580-f759-11e8-82d6-4dda28e75170.png)

**Comment by hpreston** [comment]
Closing Issue as the merge was published.
