### ISSUE TITLE
dnav3-track/rest-api-fundamentals - Postman UI changes

### ISSUE THREAD

**Issue by stgreenb** [CiscoDevNet/devnet-express-dna-issues#84]
There are some changes to Postman UI in newest versions. The one thing that stood out to a participant today was how you set up environment variables. They used to be "key" and "values", and now they "variable" and "initial (or current) values". Not hard to figure out, but the student thought they were in the wrong spot.
![image](https://user-images.githubusercontent.com/18483964/58257423-e41c1200-7d3e-11e9-880d-dde77544ca1d.png)
![image](https://user-images.githubusercontent.com/18483964/58257456-f39b5b00-7d3e-11e9-879a-792c30abe797.png)

**Comment by annegentle** [comment]
Fixed in source and published; closing.
