### ISSUE TITLE
dnav3-intro-restconf/step/3 - password & profile combination confusion

### ISSUE THREAD

**Issue by stgreenb** [CiscoDevNet/devnet-express-dna-issues#85]
Users doing this lab as part of devNet express are confused with which profile to use to login and test RestConf. They see the "RESTCONF" profile and assume that's the one they should use (even though it also says sandbox). But it points to localhost as the IP. Others assume they should be using the Devnet express CSR1 (or 2). But then the encoded username and password by default is wrong. For those devices they need to use "admin:C1sco12345" (encoded of course) but the one that's in the profile is "root:D_Vay!_10&". Maybe there is another profile they should be using, but the lab guide is unclear.

**Comment by stgreenb** [comment]
Actually in that CSR profile, the username and password are correct, but it looks like there is a hard coded base64 encoded item, so its not pulling in from the profile.

**Comment by vpralhad** [comment]
@klevenstein , any update on this issue. We still have this problem. The JSON env file needs to be modified to replace current authorization with admin:C1sco12345

**Comment by klevenstein** [comment]
I think we've resolved it; please reopen this issue if it's still a problem.
