### ISSUE TITLE
dnav3-verify/dnav3-verify/step/7

### ISSUE THREAD

**Issue by vpralhad** [CiscoDevNet/devnet-express-dna-issues#89]
When the verify.py is run, some of the users get error that leads to file verify/env_lab.py line 97 (NFVIS_SERVER). We were not really able to solve the issue and realized the error occurred cause of the indentation from line 97 to 100. When the indentation was removed and added, the issue was fixed.

**Comment by juanda2** [comment]
happened to us with a user but it turns out the user hadn't actually saved the file after changing line 36 from "sandbox" to "express", so the script was reading the original file.

**Comment by klevenstein** [comment]
Hi @vpralhad and @juanda2  - sorry about taking so long to address this. Can you review the current script at https://github.com/CiscoDevNet/dnav3-code/blob/master/env_lab.py and let me know what changes still need to be made? Thanks.

**Comment by juanda2** [comment]
looks good!

**Comment by vpralhad** [comment]
Hi @klevenstein , looks good to me as well. Please keep this issue open until the end of this week. Unfortunately, this issues was occurring randomly during the event for some of the attendees and I can only confirm it during the event this week.

**Comment by klevenstein** [comment]
DNA track has been updated. Closing this issue for now.
