### ISSUE TITLE
Guacamole times out or user loses internet , when coming back guacamole creates a clone of user 'developer'

### ISSUE THREAD

**Issue by juanda2** [CiscoDevNet/devnet-express-dna-issues#90]
Some users might lose connectivity to guacamole, when coming back, they aren't shown their initial enviornment but a clone of the environment. Some apps are tied to the original environment (i.e: postman, chrome) so they won't open in this new environment.

We tried killing processes one by one but nothing worked, the only command that worked was
 pkill -KILL -u developer 
which is issued from SSH, not from the GUI.
and it kills all open sessions, when reconnecting the user will start a fresh new login session to guacamole, and the apps are back and _saved_ files are still maintained as well, but that's not a good workaround because the user will lose all his open windows and unsaved files which could be hours of work.

This is very likely a guacamole cookie or session ID persistence issue and not a host (CentOS) issue.

**Comment by klevenstein** [comment]
Closing this issue for now; will reopen if the issue recurs.

**Comment by annegentle** [comment]
@juanda2 We do appreciate you reporting it -- it's just that there also isn't a really good place to put this type of info on the Learning Lab system itself. Please do put it in the proctor's notes for DevNet Express.
