### ISSUE TITLE
cmx-03-notifications-python 

### ISSUE THREAD

**Issue by juanda2** [CiscoDevNet/devnet-express-dna-issues#91]
When issuing the docker-compose up command, the following error is thrown:

[developer@centos ~]$ cd dnav3-code/intro-cmx/cmx-03-notifications-python/docker-compose up
bash: cd: dnav3-code/intro-cmx/cmx-03-notifications-python/docker-compose: No such file or directory
[developer@centos ~]$ cd dnav3-code/intro-cmx/cmx-03-notifications-python
[developer@centos cmx-03-notifications-python]$ docker-compose up
Starting cmxnotificationreceiver ... done
Starting ngrok ... done
Attaching to cmxnotificationreceiver, ngrok
ngrok                      | + exec ngrok http cmxnotificationreceiver:5004
cmxnotificationreceiver    | username: learning
cmxnotificationreceiver    | password: learning
cmxnotificationreceiver    | url: cmxlocationsandbox.cisco.com
cmxnotificationreceiver    | initials: df
cmxnotificationreceiver    | Traceback (most recent call last):
cmxnotificationreceiver    |   File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
cmxnotificationreceiver    |     (self.host, self.port), self.timeout, **extra_kw)
cmxnotificationreceiver    |   File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
cmxnotificationreceiver    |     raise err
cmxnotificationreceiver    |   File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
cmxnotificationreceiver    |     sock.connect(sa)
cmxnotificationreceiver    | ConnectionRefusedError: [Errno 111] Connection refused
cmxnotificationreceiver    | 
cmxnotificationreceiver    | During handling of the above exception, another exception occurred:
cmxnotificationreceiver    | 
cmxnotificationreceiver    | Traceback (most recent call last):
cmxnotificationreceiver    |   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
cmxnotificationreceiver    |     chunked=chunked)
cmxnotificationreceiver    |   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
cmxnotificationreceiver    |     conn.request(method, url, **httplib_request_kw)
cmxnotificationreceiver    |   File "/usr/local/lib/python3.6/http/client.py", line 1254, in request
cmxnotificationreceiver    |     self._send_request(method, url, body, headers, encode_chunked)
cmxnotificationreceiver    |   File "/usr/local/lib/python3.6/http/client.py", line 1300, in _send_request
cmxnotificationreceiver    |     self.endheaders(body, encode_chunked=encode_chunked)
cmxnotificationreceiver    |   File "/usr/local/lib/python3.6/http/client.py", line 1249, in endheaders
cmxnotificationreceiver    |     self._send_output(message_body, encode_chunked=encode_chunked)
cmxnotificationreceiver    |   File "/usr/local/lib/python3.6/http/client.py", line 1036, in _send_output
cmxnotificationreceiver    |     self.send(msg)
cmxnotificationreceiver    |   File "/usr/local/lib/python3.6/http/client.py", line 974, in send
cmxnotificationreceiver    |     self.connect()
cmxnotificationreceiver    |   File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 166, in connect
cmxnotificationreceiver    |     conn = self._new_conn()
cmxnotificationreceiver    |   File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
cmxnotificationreceiver    |     self, "Failed to establish a new connection: %s" % e)
cmxnotificationreceiver    | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f8b65105550>: Failed to establish a new connection: [Errno 111] Connection refused
cmxnotificationreceiver    | 
cmxnotificationreceiver    | During handling of the above exception, another exception occurred:
cmxnotificationreceiver    | 
cmxnotificationreceiver    | Traceback (most recent call last):
cmxnotificationreceiver    |   File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
cmxnotificationreceiver    |     timeout=timeout
cmxnotificationreceiver    |   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
cmxnotificationreceiver    |     _stacktrace=sys.exc_info()[2])
cmxnotificationreceiver    |   File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
cmxnotificationreceiver    |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
cmxnotificationreceiver    | urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4040): Max retries exceeded with url: /api/tunnels (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8b65105550>: Failed to establish a new connection: [Errno 111] Connection refused',))
cmxnotificationreceiver    | 
cmxnotificationreceiver    | During handling of the above exception, another exception occurred:
cmxnotificationreceiver    | 
cmxnotificationreceiver    | Traceback (most recent call last):
cmxnotificationreceiver    |   File "cmxnotificationreceiver.py", line 241, in <module>
cmxnotificationreceiver    |     verify=False)
cmxnotificationreceiver    |   File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 58, in request
cmxnotificationreceiver    |     return session.request(method=method, url=url, **kwargs)
cmxnotificationreceiver    |   File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
cmxnotificationreceiver    |     resp = self.send(prep, **send_kwargs)
cmxnotificationreceiver    |   File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
cmxnotificationreceiver    |     r = adapter.send(request, **kwargs)
cmxnotificationreceiver    |   File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
cmxnotificationreceiver    |     raise ConnectionError(e, request=request)
cmxnotificationreceiver    | requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4040): Max retries exceeded with url: /api/tunnels (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8b65105550>: Failed to establish a new connection: [Errno 111] Connection refused',))
cmxnotificationreceiver exited with code 1

**Comment by klevenstein** [comment]
CMX removed from the the DNA Center DNE v4; closing.
