### ISSUE TITLE
verify/verify.py script fails with localized ping output

### ISSUE THREAD

**Issue by cmlccie** [CiscoDevNet/devnet-express-dna-issues#93]
The scripts called by `verify/verify.py` include PING checks that depend on the output of the system PING command.  This is error-prone.  For example, if the participant's terminal is localized to Chinese (Mandarin), the verification script incorrectly reports that the pings have failed due to the fact that the output strings do not match the expected (codified strings).

Example `iosxe_tests.txt` output from a failed run of `verify.py`:
[iosxe_tests.txt](https://github.com/CiscoDevNet/devnet-express-dna-issues/files/3802770/iosxe_tests.txt)

***Note:***  We should be making API calls against these platforms not pinging them.  The intention in creating the verification scripts was two-fold:

    1. Verify that the participant's development environment is setup correctly (dependencies installed, API keys configured, etc.).
    2. Verify that the backend API resources are responding.

Running ping tests doesn't accomplish either of these objectives.  We should be making test API calls against the platforms.

**Comment by annegentle** [comment]
@kiskander  This one likely gets fixed also by using the code in https://github.com/CiscoDevNet/devnet-express-dna-issues/issues/112 -- I'd say use the code in #112  and get a two-for-one.
