### ISSUE TITLE
dnav3-track/dev-setup/dev-mac/step/2 brew cask step not needed?

### ISSUE THREAD

**Issue by fracaen** [CiscoDevNet/devnet-express-dna-issues#95]
$  brew tap caskroom/cask
Error: caskroom/cask was moved. Tap homebrew/cask-cask instead.

Quick googling seems to indicate that cask is now built into brew, and that this step is no longer required. I haven't confirmed that independently on a fresh brew install.

**Comment by klevenstein** [comment]
Fixed, closing
